### ISSUE TITLE
Add testing for all the examples in the documentation

### ISSUE THREAD

**Issue by ipeirotis** [scholarly-python-package/scholarly#102]
Add [doctest](https://docs.python.org/3/library/doctest.html) or equivalent for all examples, and add these in the test suite.

**Comment by ipeirotis** [comment]
We should also ensure that the documentation posted on  readthedocs is consistent with our releases. Probably we want to add a corresponding task in the GitHub action that posts the package on PyPI, to also post the corresponding documentation on readthedocs.

**Comment by silvavn** [comment]
Readthedocs automatically updates the documentation posted via the webhook that I setup

**Comment by ipeirotis** [comment]
> Readthedocs automatically updates the documentation posted via the webhook that I setup

Would be good to have documentation regarding that, including on how another member of the team can take a look or change the settings on readthedocs.

**Comment by arunkannawadi** [comment]
Adding doctest is a hopeless task, since the actual outputs will change with time and doctests will soon begin to fail. I have added a few more tests and checked that the docs are up to date on #378. We could close this issue with that.
