### ISSUE TITLE
Add search by author id

### ISSUE THREAD

**Issue by ipeirotis** [scholarly-python-package/scholarly#106]
The (stale) PR https://github.com/OrganicIrradiation/scholarly/pull/46/ suggested adding a search by author_id, which is useful functionality when we know the author's profile and want to get details for an individual directly, instead of doing an author search first.

**Comment by TomBrien** [comment]
I have this working in a forked repo of the new codebase. The code is probably not 100 % correct to the base here but I can add a PR. Which branch should a target `develop`?

**Comment by ipeirotis** [comment]
Create a new branch, call it `issue_106` or so, and then issue a PR against `develop`.

**Comment by TomBrien** [comment]
Looks like the code is changing quite fast at the moment and I’m guessing it’s mid way through a complete overhaul? If so I’ll hold of a little until it’s stabilised a little. Thanks for reviving this by the way

**Comment by TomBrien** [comment]
In fact, `search_pubs` seems completely broken (just hangs) for me on both the current `master` and `develop` branches. Is this a known issue?

**Comment by ipeirotis** [comment]
Have you tried it with proxies/Tor?

**Comment by TomBrien** [comment]
Yep looks like anything calling `_SearchScholarIterator` is just hanging including when using proxies.

MWE:
```python
from fp.fp import FreeProxy
from scholarly import scholarly

proxy = FreeProxy(rand=True, timeout=1, country_id=['US', 'CA']).get()
scholarly.use_proxy(http=proxy, https=proxy)

search_query = scholarly.search_pubs('Perception of physical stability and center of mass of 3D objects')
```

**Comment by ipeirotis** [comment]
@TomBrien Using FreeProxies is not the most reliable option but it works.

I have a working example at https://github.com/scholarly-python-package/scholarly/issues/120 showing that you need to keep switching proxies to achieve your goal.

Take a look and let me know.

We just posted the new version on PyPI, so now would be a good time to issue your PR for the new functionality.

**Comment by TomBrien** [comment]
Ok shall do that over the weekend. I ran that code and it worked but it took 8 attempts to find a working proxy but it did work nicely then

**Comment by silvavn** [comment]
@TomBrien I realized that there was an url error when using `_SearchScholarIterator`, latest `develop` release should have it fixed :)
