### ISSUE TITLE
Solution to work around 429 Timeouts

### ISSUE THREAD

**Issue by emilepetrone** [scholarly-python-package/scholarly#109]
In running Scholarly today, I hit many Timeouts. The program would then sit there at a stalemate with Scholar.  

Is there a solution for working around Timeouts? My logs haven't shown captchas, so maybe this is the new behavior? 

Anyone else getting Timeouts?

**Comment by ipeirotis** [comment]
I would strongly recommend using Tor.

What system are you using? Mac, Linux, Windows?

**Comment by emilepetrone** [comment]
> I would strongly recommend using Tor.
> 
> What system are you using? Mac, Linux, Windows?

Mac. That may be part of it.

**Comment by ipeirotis** [comment]
Try installing Tor. I am not sure in which port Tor runs by default on Mac. You are likely to need to set the proxies manually.

There is an extra level of protection when we configure scholarly to reset the Tor proxy when Google Scholar returns an error. For that part, you need to setup a ControlPort for Tor and a password (we do that for Linux using this script https://github.com/scholarly-python-package/scholarly/blob/master/setup_tor.sh)

I understand that the Tor part is still very rough. We are working to make that part much smoother.

**Comment by emilepetrone** [comment]
Thansk @ipeirotis I believe I got it running in a Linux virtualbox. Closing the ticket for now. Thanks again!

**Comment by emilepetrone** [comment]
UPDATE: I was able to get tor setup on Mac, but I still can hit the 429s. Trying to find a solution.

**Comment by ipeirotis** [comment]
You will still hit errors with Tor. Refreshing the id in tor and waiting can often make a difference

**Comment by emilepetrone** [comment]
I was using the older code. Updated to the current scholarly and added:

```
scholarly.launch_tor('tor', 9050, 9051)
scholarly.use_tor(9050, 9051, "scholarly_password")
```

I can see the tor process launching so I believe I'm back in action.

**Comment by ipeirotis** [comment]
You should not run `use_tor` together with `launch_tor`.

The `launch_tor` creates a Tor instance within scholarly, without any password for the control port.

The `use_tor` relies on an externally launched Tor server, that has been configured with a torrc file and with the password "scholarly_password" as the password for the control port (see https://github.com/scholarly-python-package/scholarly/blob/master/setup_tor.sh for an example that creates the torrc)
