### ISSUE TITLE
AttributeError: 'Publication' object has no attribute 'url_scholarbib'

### ISSUE THREAD

**Issue by rbiele02** [scholarly-python-package/scholarly#113]
I would like to read out the name of the Journal for some publications. However when I run

`
search_query = scholarly.search_pubs_query('Perception of physical stability and center of mass of 3D objects')
print(next(search_query))

[1]:  

{'_filled': False,
 'bib': {'abstract': 'Humans can judge from vision alone whether an object is '
                     'physically stable or not. Such judgments allow observers '
                     'to predict the physical behavior of objects, and hence '
                     'to guide their motor actions. We investigated the visual '
                     'estimation of physical stability of 3-D objects (shown '
                     'in stereoscopically viewed rendered scenes) and how it '
                     'relates to visual estimates of their center of mass '
                     '(COM). In Experiment 1, observers viewed an object near '
                     'the edge of a table and adjusted its tilt to the '
                     'perceived critical angle, ie, the tilt angle at which '
                     'the object …',
         'author': 'SA Cholewiak and RW Fleming and M Singh',
         'eprint': 'https://jov.arvojournals.org/article.aspx?articleID=2213254',
         'title': 'Perception of physical stability and center of mass of 3-D '
                  'objects',
         'url': 'https://jov.arvojournals.org/article.aspx?articleID=2213254'},
 'source': 'scholar'}
`

I don't get any information of the Journal. By using the fill() function I get the following error:

`search_query = scholarly.search_pubs_query('Perception of physical stability and center of mass of 3D objects')

print(next(search_query).fill())

[2:]

AttributeError                            Traceback (most recent call last)
<ipython-input-119-29d4cd1b06f2> in <module>
      1 search_query = scholarly.search_pubs_query('Perception of physical stability and center of mass of 3D objects')
----> 2 print(next(search_query).fill())

/opt/anaconda3/lib/python3.7/site-packages/scholarly/scholarly.py in fill(self)

AttributeError: 'Publication' object has no attribute 'url_scholarbib'
`

Any ideas? 
Thanks in advance

**Comment by silvavn** [comment]
Please refer to the latest commit 49f3480d808a89833fb85782e955b0a029dca0ac
if the journal name is available it will be under 
```python
p.bibtex['venue']
```
or
```python
p.bibtex['journal']
```
where `p` is an instance of `Publication`

**Comment by ipeirotis** [comment]
I think this is fixed.

```python
from scholarly import scholarly
search_query = scholarly.search_pubs('Perception of physical stability and center of mass of 3D objects')
p = next(search_query)
print(p)
```

returns

```
{'bib': {'abstract': 'Humans can judge from vision alone whether an object is '
                     'physically stable or not. Such judgments allow observers '
                     'to predict the physical behavior of objects, and hence '
                     'to guide their motor actions. We investigated the visual '
                     'estimation of physical stability of 3-D objects (shown '
                     'in stereoscopically viewed rendered scenes) and how it '
                     'relates to visual estimates of their center of mass '
                     '(COM). In Experiment 1, observers viewed an object near '
                     'the edge of a table and adjusted its tilt to the '
                     'perceived critical angle, ie, the tilt angle at which '
                     'the object',
         'author': ['SA Cholewiak', 'RW Fleming', 'M Singh'],
         'cites': '23',
         'eprint': 'https://jov.arvojournals.org/article.aspx?articleID=2213254',
         'gsrank': '1',
         'title': 'Perception of physical stability and center of mass of 3-D '
                  'objects',
         'url': 'https://jov.arvojournals.org/article.aspx?articleID=2213254',
         'venue': 'Journal of vision',
         'year': '2015'},
 'citations_link': '/scholar?cites=15736880631888070187&as_sdt=5,33&sciodt=0,33&hl=en',
 'filled': False,
 'source': 'scholar',
 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3DPerception%2Bof%2Bphysical%2Bstability%2Band%2Bcenter%2Bof%2Bmass%2Bof%2B3D%2Bobjects%26hl%3Den%26as_sdt%3D0,33&citilm=1&json=&update_op=library_add&info=K8ZpoI6hZNoJ&ei=2b8sX-TIBpqGy9YPgY6TqAw',
 'url_scholarbib': '/scholar?q=info:K8ZpoI6hZNoJ:scholar.google.com/&output=cite&scirp=0&hl=en'}
```

So, I see the journal name under `venue`, with the value `Journal of vision`
