### ISSUE TITLE
Add FreeProxy example in the documentation

### ISSUE THREAD

**Issue by ipeirotis** [scholarly-python-package/scholarly#120]
The following example shows how to use proxies to overcome network difficulties. Would be good to have in the documentation so that we can point there for people that face network issues, without asking them to install Tor. It is still *very* slow (you may need to go through 10-20 proxies to get it to work until the end) but it does not hang.

```python
from fp.fp import FreeProxy
from scholarly import scholarly

def set_new_proxy():
    while True:
        proxy = FreeProxy(rand=True, timeout=1).get()
        proxy_works = scholarly.use_proxy(http=proxy, https=proxy)
        if proxy_works:
            break
    print(proxy)
    return proxy    

set_new_proxy()

while True:
    try:
        search_query = scholarly.search_pubs('Perception of physical stability and center of mass of 3D objects')
        print("Got the results of the query")
        break
    except Exception as e:
        set_new_proxy() 
    
pub = next(search_query)
print(pub)

while True:
    try:
        filled = pub.fill()
        print("Filled the publication")
        break
    except Exception as e:
        set_new_proxy() 
    
print(filled)
```

**Comment by sngabha** [comment]
I tried using FreeProxy with my mac and I am still getting the same error.
Can anyone help me with this issue?

`---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-21-c6681f3f520f> in <module>
      1 paper_title = 'Perception of physical stability and center of mass of 3D objects'
----> 2 search_query = scholarly.search_pubs(paper_title)

/Library/Python/3.7/site-packages/scholarly/_scholarly.py in search_pubs(self, query, patents, citations, year_low, year_high)
    150         # improve str below
    151         url = url + yr_lo + yr_hi + citations + patents
--> 152         return self.__nav.search_publications(url)
    153 
    154     def search_single_pub(self, pub_title: str, filled: bool = False):

/Library/Python/3.7/site-packages/scholarly/_navigator.py in search_publications(self, url)
    345         :rtype: {_SearchScholarIterator}
    346         """
--> 347         return _SearchScholarIterator(self, url)

/Library/Python/3.7/site-packages/scholarly/publication.py in __init__(self, nav, url)
     22         self._url = url
     23         self._nav = nav
---> 24         self._load_url(url)
     25 
     26     def _load_url(self, url: str):

/Library/Python/3.7/site-packages/scholarly/publication.py in _load_url(self, url)
     26     def _load_url(self, url: str):
     27         # this is temporary until setup json file
---> 28         self._soup = self._nav._get_soup(url)
     29         self._pos = 0
     30         self._rows = self._soup.find_all('div', class_='gs_r gs_or gs_scl')

/Library/Python/3.7/site-packages/scholarly/_navigator.py in _get_soup(self, url)
    290     def _get_soup(self, url: str) -> BeautifulSoup:
    291         """Return the BeautifulSoup for a page on scholar.google.com"""
--> 292         html = self._get_page(_HOST.format(url))
    293         html = html.replace(u'\xa0', u' ')
    294         res = BeautifulSoup(html, 'html.parser')

/Library/Python/3.7/site-packages/scholarly/_navigator.py in _get_page(self, pagerequest)
    127                 # to avoid an infinite loop
    128                 tries += 1
--> 129         raise Exception("Cannot fetch the page from Google Scholar.")
    130 
    131     def _check_proxy(self, proxies) -> bool:

Exception: Cannot fetch the page from Google Scholar.`

**Comment by ipeirotis** [comment]
Did you try using the code above?

**Comment by sngabha** [comment]
> Did you try using the code above?

Yes, and I am getting some exception when I went through scholar.log. This issue contains the logs - https://github.com/scholarly-python-package/scholarly/issues/140 .
I am able to create a proxy using both tor and FreeProxy. But FreeProxy is giving me above exception and Tor is not even giving any exception - Exception: Cannot fetch the page from Google Scholar.

**Comment by ipeirotis** [comment]
The behavior is not unexpected. It takes some time until finding a proxy or Tor exit node that works.
