### ISSUE TITLE
A kind request

### ISSUE THREAD

**Issue by hazerb** [scholarly-python-package/scholarly#129]
Hello to all of you, we are students of Boğaziçi university in Turkey. We are currently using your package for a lesson project. But every change you make prevents our functions from working. We would be glad if you don't change the names of your functions in the next 3 weeks.
We would also be grateful if you do not change the content of functions.Also, I wonder when will you finalize the code if the change is necessary? If we could not use your package, we'll get zero.The functions are working very well right now.Thanks for your big effort.

**Comment by silvavn** [comment]
Hello!
Its nice to hear that you are using scholarly.
My advice to you is: download a version and install it locally. That way, even if we change anything (which will most likely happen since we are developing continuously) you have the current version up and running!

Good luck with your project :)

**Comment by ipeirotis** [comment]
> Hello to all of you, we are students of Boğaziçi university in Turkey. We are currently using your package for a lesson project. But every change you make prevents our functions from working. We would be glad if you don't change the names of your functions in the next 3 weeks.
> 
> We would also be grateful if you do not change the content of functions.Also, I wonder when will you finalize the code if the change is necessary? If we could not use your package, we'll get zero.The functions are working very well right now.Thanks for your big effort.

If you want to use a stable version then perhaps you want to fix the version of the library when you download it using pip

For example, to keep the version that has been released last August, use the command:

pip install scholarly=0.2.5

If you want to use the latest version from Github please understand that the latest version is not guaranteed to be stable and there may be things that will be changing until we manage to get them to work properly.

Finally, this project is still in alpha stage of development. Once we get it to be stable enough, we will freeze the APi and release version 1.0beta to check that everything works properly, before releasing version 1.0.
