### ISSUE TITLE
 No url_picture attribute for coauthors

### ISSUE THREAD

**Issue by LikDioxo** [scholarly-python-package/scholarly#132]
Could you add the ability to get url_picture from co-authors after fill (['coauthors'])?

**Comment by ipeirotis** [comment]
Code that replicates the issue:

```python
search_query = scholarly.search_author('Steven A. Cholewiak')
author = next(search_query).fill()
print(f"Author '{author.name}' has pic:", hasattr(author , 'url_picture'))
co_author = author.coauthors[0].fill()
print(f"Co-author '{co_author.name}' has pic:", hasattr(co_author , 'url_picture'))
```

**Comment by ipeirotis** [comment]
Potentially, we can do that faster if we use the image URL for the co-authors from the main author's 
page.

In the main author page, the URLs for the images are of the form:

https://scholar.googleusercontent.com/citations?view_op=small_photo&user=oQHsB5kAAAAJ&citpid=5

To get the bigger version, we can change the `view_op` parameter from `small_photo` to `medium_photo`

https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=oQHsB5kAAAAJ&citpid=5

**Comment by ipeirotis** [comment]
Fixed in v.1.0.3
