### ISSUE TITLE
.fill() fails if class_='gsh_small' does not exist

### ISSUE THREAD

**Issue by tarensanders** [scholarly-python-package/scholarly#133]
Some papers don't have abstracts but still have the 'description' key. E.g., there is a description key [here](https://scholar.google.com/citations?hl=en&view_op=view_citation&citation_for_view=PaGo64YAAAAJ:H6myOybQgeYC), but no class called 'gsh_small'.

This causes the following part of publication.py to fail.
```python
elif key == 'description':
	if val.text[0:8].lower() == 'abstract':
		val = val.text[9:].strip()
	abstract = val.find(class_='gsh_csp')
	if abstract is None:
		abstract = val.find(class_='gsh_small')
	self._abstract = abstract.text
```

Seems like there's a couple of ways to solve this. For example

```python
elif key == 'description':
	if val.text[0:8].lower() == 'abstract':
		val = val.text[9:].strip()
	abstract = val.find(class_='gsh_csp')
	if abstract is None:
		abstract = val.find(class_='gsh_small')
	if abstract:
		self._abstract = abstract.text
	else:
		self._abstract = None
```

Let me know if you want me to submit this as a PR.

**Comment by emilepetrone** [comment]
That would be great. I just noticed this yesterday.
