### ISSUE TITLE
The `Publication.citedby` command executes too many network calls

### ISSUE THREAD

**Issue by ipeirotis** [scholarly-python-package/scholarly#137]
When we are trying to retrieve the citations that cite a particular paper, the current code fills in each publication by default, by fetching the URL that retrieves the bibtex entry. That behavior should be reserved only for when we fill the publication.

**Comment by stefanct** [comment]
Not sure if I concur with your diagnosis entirely (i.e. I have no idea what you mean exactly with "`.cites` command" :) but please take a look at the referenced change above. It is very much untested but seems to do what we were discussing in #131.

**Comment by stefanct** [comment]
The previous version of the patch was wrong after all. But now the tests pass and everything seems hunky-dory :)

**Comment by ipeirotis** [comment]
Tests fail with `ModuleNotFoundError: No module named 'selenium'`

Also, please target the `develop` branch. We will be merging with `master` when we are ready for a new release.
