### ISSUE TITLE
'Publication' object has no attribute 'get_citedby'

### ISSUE THREAD

**Issue by sngabha** [scholarly-python-package/scholarly#141]
I am trying to call the get_citedby function of publication, but getting an error that this function does not exists.
I am following the example code provided here - https://scholarly.readthedocs.io/en/latest/quickstart.html#example 

Please help me with this issue.

Thanks!

**Comment by arafeh94** [comment]
I'm trying the same thing with the fix you mentions, but now I'm getting
**'Publication' object has no attribute 'citations_link' error** 

`
Getting https://scholar.google.com/citations?hl=en&view_op=view_citation&citation_for_view=4bahYMkAAAAJ:u5HHmVD_uO8C
Traceback (most recent call last):
  File "PATH", line 233, in <module>
    print([citation.bib['title'] for citation in pub.citedby])
  File "PATH\venv\lib\site-packages\scholarly\publication.py", line 246, in citedby
    return _SearchScholarIterator(self.nav, self.citations_link)
AttributeError: 'Publication' object has no attribute 'citations_link'
Process finished with exit code 1`

can you please help ? 
thanks

**Comment by davidwozabal** [comment]
I have exactly the same issue as arafeh94 with `citedby()`.

> AttributeError: 'Publication' object has no attribute 'citations_link'

**Comment by lukezsmith** [comment]
> Replace `get_citedby` with `citedby`. We need to fix that part of the documentation.

(Disclaimer: Apologies in advance for any open source contribution faux pas in this comment, this is my first attempt at working on an open source project!)

As others have mentioned, publications of the source 'citations' ([example URL of such a publication with 'citations' as the source attribute of the publication](https://scholar.google.com/citations?hl=en&user=4bahYMkAAAAJ&pagesize=100#d=gs_md_cita-d&u=%2Fcitations%3Fview_op%3Dview_citation%26hl%3Den%26user%3D4bahYMkAAAAJ%26pagesize%3D100%26citation_for_view%3D4bahYMkAAAAJ%3Au5HHmVD_uO8C%26tzom%3D-60)) result in an AttributeError: 'Publication' object has no attribute 'citations_link', this is because these publications don't get assigned a link to citations as a Publication object in publication.py as publications of the source 'scholar' do. Is there a reason for this? I'm just asking as I was going to work on a fix for this issue by assigning a citations_link attribute for 'citations'-sourced publications which could fix this issue but wanted clarification on whether there was a reason citations_link is not assigned to 'citations'-sourced documents.

Thanks

**Comment by silvavn** [comment]
This code works without error for me:

```python
from scholarly import scholarly

papers = [a for a in scholarly.search_pubs('On the development of intelligent agents for moba games')]
for i in papers:
    for j in i.citedby:
        print(j)
```

**Comment by lukezsmith** [comment]
> This code works without error for me:
> 
> ```python
> from scholarly import scholarly
> 
> papers = [a for a in scholarly.search_pubs('On the development of intelligent agents for moba games')]
> for i in papers:
>     for j in i.citedby:
>         print(j)
> ```

Wouldn't it be beneficial to implement a fix that allows you to see citations for a publication gathered from an author search (as in the quickstart documentation?) I can work on this if so

**Comment by silvavn** [comment]
@lukezsmith that creates too many requests depending on the author, so I would discourage that. If you for example search for an author that has the paper in the image below: 
![image](https://user-images.githubusercontent.com/37382997/84206947-776cd600-aa6d-11ea-960d-5bca53fea819.png)
On 10 papers per page that is more than 1700 requests... so I would be very careful about going down that road, unless you filter to the first n pages or something. 
We have the exact same problem with the pubs search right now. When you use a term that is too open it creates too many requests.

**Comment by davidwozabal** [comment]
@lukezsmith thank you for this reply. Unfortunately, your request

`scholarly.search_pubs('On the development of intelligent agents for moba games')`

results in the error

> Exception: Cannot fetch the page from Google Scholar.

for me (all other functions fetching, e.g., author information, work fine). Do I need a proxy or TOR for this request?

**Comment by davidwozabal** [comment]
@silvavn I am not sure whether I see the point regarding the many requests. The paper you cited as an example, will always create 1700 requests, irrespective if you get the paper object from an author search or from an publication search. 

I therefore think it would be a good idea to implement the functionality proposed by lukezsmith.

**Comment by silvavn** [comment]
@davidwozabal I agree that this could be implemented, again with the caveat of limiting the number of papers to be retrieved. See #137

**Comment by silvavn** [comment]
> @lukezsmith thank you for this reply. Unfortunately, your request
> 
> `scholarly.search_pubs('On the development of intelligent agents for moba games')`
> 
> results in the error
> 
> > Exception: Cannot fetch the page from Google Scholar.
> 
> for me (all other functions fetching, e.g., author information, work fine). Do I need a proxy or TOR for this request?

Yes, your ip is probably blocked by google for making too many requests.

**Comment by fdmatoz** [comment]
Hi same problem here. The tool is great! thanks! I followed the suggestions here also looked at the code but nothing:
`from scholarly import scholarly
search_query = scholarly.search_author('Steven H. Strogatz')
author = next(search_query).fill()

# Print the titles of the author's publications
#print([pub.bib['title'] for pub in author.publications])

# Take a closer look at the first publication
pub = author.publications[0].fill()
print(pub)

# Which papers cited that publication?
print(pub.citedby)`

two things: 

(1) **Take a closer look at the first publication** is not the first publication but rather the most cited one
(2) print(pub.citedby)  :  

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-6556eb84c2be> in <module>
     11 
     12 # Which papers cited that publication?
---> 13 print(pub.citedby)

~/.miniconda3/envs/ast/lib/python3.7/site-packages/scholarly/publication.py in citedby(self)
    244         if not self.filled:
    245             self.fill()
--> 246         return _SearchScholarIterator(self.nav, self.citations_link)
    247 
    248     @property

AttributeError: 'Publication' object has no attribute 'citations_link'

any ideas?

thanks again for all the effort!

**Comment by arafeh94** [comment]
> Hi same problem here. The tool is great! thanks! I followed the suggestions here also looked at the code but nothing:
> `from scholarly import scholarly
> search_query = scholarly.search_author('Steven H. Strogatz')
> author = next(search_query).fill()
> 
> # Print the titles of the author's publications
> #print([pub.bib['title'] for pub in author.publications])
> 
> # Take a closer look at the first publication
> pub = author.publications[0].fill()
> print(pub)
> 
> # Which papers cited that publication?
> print(pub.citedby)`
> 
> two things:
> 
> (1) **Take a closer look at the first publication** is not the first publication but rather the most cited one
> (2) print(pub.citedby) :
> 
> AttributeError Traceback (most recent call last)
> in
> 11
> 12 # Which papers cited that publication?
> ---> 13 print(pub.citedby)
> 
> ~/.miniconda3/envs/ast/lib/python3.7/site-packages/scholarly/publication.py in citedby(self)
> 244 if not self.filled:
> 245 self.fill()
> --> 246 return _SearchScholarIterator(self.nav, self.citations_link)
> 247
> 248 @Property
> 
> AttributeError: 'Publication' object has no attribute 'citations_link'
> 
> any ideas?
> 
> thanks again for all the effort!

This simple solution should work until we have a valid fix. 
in publication.py file add this code after line 219 in "fill" function

`
                    self.citations_link = str(val.find('a')['href']).replace("https://scholar.google.com", "")
`

it should be like 

`elif key == 'total citations':
                    self.bib['cites'] = re.findall(_SCHOLARPUBRE, val.a['href'])[0]
                    self.citations_link = str(val.find('a')['href']).replace("https://scholar.google.com", "")`
