### ISSUE TITLE
`StopIteration` terminates any call to `next(search_query).fill()` - how to debug?

### ISSUE THREAD

**Issue by jowens** [scholarly-python-package/scholarly#142]
First, super cool package. I hope I can figure out how to use it. I would appreciate guidance in 

I have only tried to use scholarly with FreeProxy and Tor. I believe I'm using these correctly:

```python
# scholarly uses tor
scholarly.launch_tor("/opt/local/bin/tor", tor_sock_port=9050, tor_control_port=9051)
# this is MacOS MacPorts's tor
```
OR
```python
# scholarly uses FreeProxy
proxy = FreeProxy(rand=True, timeout=1, country_id=["US", "CA"]).get()
scholarly.use_proxy(http=proxy, https=proxy)
```

(note: the documentation says I can call `launch_tor` with only one argument, the binary, but it appears to require 3 arguments)

I'm calling this as

```
search_query = scholarly.search_author("full name of author")
author = next(search_query).fill()    # here's where the StopIteration happens
print(author)
```

Anyway, I've done this a dozen or so times each with tor and FreeProxy and it never completes. All I get is `StopIteration` and I don't have any other info with which to debug. Am I doing this right? Is there any ability for me to debug further? If the "full name of author" is a well-cited person, does that make it harder to complete successfully? (Is there a way to split up the query if that's the case?)

**Comment by Nicholas-Lewis-USDA** [comment]
Go to google scholars and search for your author manually (confirm there is a solution) 
Assuming manual shows up with results the problem will be with your proxies.

A null set was returned and thus when you tried to fill it results in that error.

Debug help:
`try:
     Your code
except Exception as Err:
     print(err)
else:
     rest of code`

Loop your code from top to bottom until you find the source of your error.

I highly recommend you use something like Visual Studio Code (Free) and include the python extension for easy linting.   This way you use can use breakpoints and debug easier without the above debug tool.

**Comment by jowens** [comment]
Thank you, this was helpful. I believe (after testing) that if your query in Google Scholar does not put a "User profiles for" at the top, then you'll get the error I saw. I was able to fix the problem with a different query string and everything is now working as advertised. Thank you for this excellent debugging tipsheet. I appreciate it. Keep being awesome!
