### ISSUE TITLE
bibtex retrieval (might be) actually not needed

### ISSUE THREAD

**Issue by silvavn** [scholarly-python-package/scholarly#146]
![image](https://user-images.githubusercontent.com/37382997/84184006-e3d5de00-aa49-11ea-8f60-27ab300a874a.png)

We might actually not need to retrieve the bib at all since we have the information in the main page (see image above). We might just need to parse that information to fill the profile. @ipeirotis

**Comment by ipeirotis** [comment]
Seems a lot of work to implement parsing logic for these entries. I will mark this issue as "wontfix / closed", and we can reopen in the future if it seems that this is required.
