### ISSUE TITLE
Example "scholarly.search_pubs" not working expectedly

### ISSUE THREAD

**Issue by JiayuanDing100** [scholarly-python-package/scholarly#147]
Tried the search_pubs sample code, but it doesn't work expectedly
from fp.fp import FreeProxy
from scholarly import scholarly
proxy = FreeProxy(rand=True, timeout=1, country_id=['US', 'CA']).get()
scholarly.use_proxy(http=proxy, https=proxy)

search_query = scholarly.search_pubs('Perception of physical stability and center of mass of 3D objects')
print(next(search_query))

Exception: Cannot fetch the page from Google Scholar.

**Comment by ipeirotis** [comment]
You need to catch the exception and try again. I updated the example code in the README.
