### ISSUE TITLE
bibtexparser error - provided correction

### ISSUE THREAD

**Issue by Nicholas-Lewis-USDA** [scholarly-python-package/scholarly#149]
common_strings wasn't turned on and thus 'nov' was causing errors.

in publications.py added line 6 to be `parser = bibtexparser.bparser.BibTexParser(common_strings=True)`

in line 233(old 232) to be `self.bib.update(bibtexparser.loads(bibtex,parser).entries[0])`

**Comment by silvavn** [comment]
Can you propose a push request with your modifications?

**Comment by ipeirotis** [comment]
Fixed: https://github.com/scholarly-python-package/scholarly/blob/4d4b120c044aefea90e84728cff8c17fca21439b/scholarly/publication_parser.py#L321
