### ISSUE TITLE
return utf-8 results

### ISSUE THREAD

**Issue by Nicholas-Lewis-USDA** [scholarly-python-package/scholarly#151]
Newer updates are leaving my answers with {"\\e} and other examples in the name and I have yet to find a way to replace the letters.  

In your own documentation(recently updated) it also shows 

> author = {Ester, Martin and Kriegel, Hans-Peter and Sander, J{\"o}rg and Xu, Xiaowei},

This is done when looking at authors in a publication

**Comment by silvavn** [comment]
so, what you exemplified above is Latex notation `\"o` will result in `ö`. In other cases the notation might be unicode escaped, and you can easily convert that to utf-8 using python.

**Comment by Nicholas-Lewis-USDA** [comment]
could you provide how? I have looked at python's documentation for both as both seem to be used and I can't make heads or tails of it.

**Comment by silvavn** [comment]
Yes, can you provide a sample of the code that you are using?

**Comment by Nicholas-Lewis-USDA** [comment]
```
search_query = scholarly.search_author(author_name)
author = next(search_query).fill()
print(author.bib['author'])
```
That should be enough context to get to a solution I need.

**Comment by silvavn** [comment]
That code will not work. You are trying to get a bib from an author. Author
objects have no bib.

Victor Silva

This message was typed and sent from a mobile phone. Please excuse any
typos.

**Comment by Nicholas-Lewis-USDA** [comment]
You may not have got my edit, I changed author.bib[‘author’] after  I noticed I forgot the “s” at the end.

> search_query = scholarly.search_author(author_name)
> author = next(search_query).fill()
> print(author.bib['author's])


[USDA - APHIS]
Nick Lewis
Computer Clerk
APHIS Marketing and Regulatory Programs Business Services (MRPBS)
MRP Information Technology (MRP IT) Services
Laboratory and Scientific IT Services
p: 515-337-7507 c: 515-520-9131
nicholas.lewis@usda.gov<mailto:nicholas.lewis@usda.gov>
1920 Dayton Ave
Ames, IA 50010

**Comment by silvavn** [comment]
I think I wasn't clear.
`search_author` returns an object of the `Author` class. Then you fill it with `.fill()`. However the object of `Author` has no attibute `.bib` because only objects of the `Publication` class have bibtex representations.

If you provide me with the exact code that you are having problems with, I will be more empowered to help you.

**Comment by Nicholas-Lewis-USDA** [comment]
Sorry here is quick program I made to get the results in question

```
search_query = scholarly.search_pubs("Antemortem detection of chronic wasting disease prions in nasal brush collections and rectal biopsy specimens from white-tailed deer by real-time quaking-induced conversion")
pub = next(search_query).fill()
print(pub.bib['author'])
```
Output: Haley, Nicholas J and Siepker, Chris and Walter, W David and Thomsen, Bruce V and Greenlee, Justin J and Lehmkuhl, Aaron D and Richt, J{\"u}rgen A

**Comment by silvavn** [comment]
My suggestion is use regex to remove `{\.` and `}` characters from the author field.
eg. use `{\\.` and `}` as regular expressions.

**Comment by Nicholas-Lewis-USDA** [comment]
you were correct on latex being used.
`pip install pylatexenc`

```
from pylatexenc.latex2text import LatexNodes2Text 
print(LatexNodes2Text().latex_to_text({latex string}))
```
This will result in the letters being converted back and then you can do whatever you want from there.

My example {\\"u} gets translated back to ü using this method.  This has also cleared up many other issues I had with other characters not coming back correctly.  I will need to test with other language sets.

Thank you @silvavn
