### ISSUE TITLE
search_pubs() method not working

### ISSUE THREAD

**Issue by alexmaina** [scholarly-python-package/scholarly#153]
It seems that the `scholarly.search_pubs()` is broken. For example, the code snippet below returns `Exception: Cannot fetch the page from Google Scholar.`

```
from fp.fp import FreeProxy
from scholarly import scholarly

query = scholarly.search_pubs("A density-based algorithm for discovering clusters in large spatial databases with noise")
print(next(query))
```
On the other hand the `scholarly.search_author()` method  and `scholarly.search_keyword() `work well and return results

**Comment by Nicholas-Lewis-USDA** [comment]
Check your FreeFroxy settings

`print(next(query)) ` is causing your error as query returned with no results and thus can't iterate.  

I have found it extremely helpful to add the following to my code as I test and even use this program.

```
from random import randint
from time import sleep
def sleeper():
     sleeper = randint(10,30)
     print("sleeping: "+str(sleeper))
     sleep(sleeper)
```

call this function anytime you call a search and or fill and should help to keep Google happier.

**Comment by Nicholas-Lewis-USDA** [comment]
Also, I am not allowed to use proxies, so I am not sure if you are using it correct based on documentation.  But your exception tells me Google is giving you a timeout right now.  It should allow you back in 5 minutes to 24 hours depending on how bad and how much you keep hitting their servers.

**Comment by Nicholas-Lewis-USDA** [comment]
Your results minus the import and use of proxy.  So the code is working you / proxy are just in a timeout room.

```
{'bib': {'abstract': 'Clustering algorithms are attractive for the task of '
                     'class identification in spatial databases. However, the '
                     'application to large spatial databases rises the '
                     'following requirements for clustering algorithms: '
                     'minimal requirements of domain knowledge to determine '
                     'the input',
         'author': ['M Ester', 'HP Kriegel', 'J Sander', 'X Xu'],
         'cites': '17912',
         'eprint': 'https://www.aaai.org/Papers/KDD/1996/KDD96-037.pdf?source=post_page---------------------------',
         'gsrank': '1',
         'title': 'A density-based algorithm for discovering clusters in large '
                  'spatial databases with noise.',
         'url': 'https://www.aaai.org/Papers/KDD/1996/KDD96-037.pdf?source=post_page---------------------------',
         'venue': 'Kdd',
         'year': '1996'},
 'citations_link': '/scholar?cites=9374625445873167608&as_sdt=5,33&sciodt=0,33&hl=en',
 'filled': False,
 'source': 'scholar',
 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3DA%2Bdensity-based%2Balgorithm%2Bfor%2Bdiscovering%2Bclusters%2Bin%2Blarge%2Bspatial%2Bdatabases%2Bwith%2Bnoise%26hl%3Den%26as_sdt%3D0,33&citilm=1&json=&update_op=library_add&info=-KybkyxcGYIJ&ei=HBjyXofhOMuAy9YPl9iVyAI',
 'url_scholarbib': 'https://scholar.googleusercontent.com/scholar.bib?q=info:-KybkyxcGYIJ:scholar.google.com/&output=citation&scisdr=CgUpOux_GAA:AAGBfm0AAAAAXvIaeezyKz-fgQcui2uT9nKiKpzvvxpO&scisig=AAGBfm0AAAAAXvIaeYAxZfoIM3_qZvd04mwdsMibcfFT&scisf=4&ct=citation&cd=-1&hl=en'}
```

**Comment by alexmaina** [comment]
I am working on a home machine. There are no firewalls installed. It seems as you suggest that Google is giving me a timeout every time i try to run the script.

**Comment by Nicholas-Lewis-USDA** [comment]
It could be you, your ISP, and or the Proxy if it is that easy to use and run.  Maybe take off the import and see if it fairs better?

**Comment by alexmaina** [comment]
I am working on a home machine. There are no firewalls installed. It seems as you suggest that Google is giving me a timeout every time i try to run the script.

**Comment by alexmaina** [comment]
Removing the proxy seems to work "for now". I hope it continues to work successfully.

**Comment by Nicholas-Lewis-USDA** [comment]
Like I said, I would strongly consider using the following code to slow down the requests
```
from random import randint
from time import sleep
def get_sleeper():
     sleeper = randint(10,30)
     print("sleeping: "+str(sleeper))
     sleep(sleeper)
```

```
from scholarly import scholarly
query = scholarly.search_pubs("A density-based algorithm for discovering clusters in large spatial databases with noise")
get_sleeper()
print(next(query).fill())
```

noticed I added the .fill() and thus I added a sleeper in front since the search was done before and I need to add a small delay.

**Comment by alexmaina** [comment]
Thank you.
