### ISSUE TITLE
Getting the exception Cannot fetch the page from Google Scholar

### ISSUE THREAD

**Issue by davidrol6** [scholarly-python-package/scholarly#156]
Dear all,

I worked on a script using Scholarly a month ago and it worked perfectly. Today I am trying to rerun the script but I keep getting the same exception everytime I invoke the function search_pubs. What is happening?

I am using version 0.3.3.

Thanks!

**Comment by Nicholas-Lewis-USDA** [comment]
Will need code to know more

**Comment by davidrol6** [comment]
I was just doing a simple test:

`from scholarly import scholarly`
`pubs = scholarly.search_pubs("a new dawn for citizen science")`
`print(next(pubs))`

The exception raises in the second line,

**Comment by Nicholas-Lewis-USDA** [comment]
Then that is your answer.  You can try to load a browser and see if you can solve it.  Or wait 1-48 hours for your minor ban to be lifted.  Or use proxies / Tor to try to go around it possibly.

**Comment by davidrol6** [comment]
Solved it by using Tor. I was a little bit confused since last time I didn't have to do anything else.
Thanks!
