### ISSUE TITLE
Navigator raises generic Exception

### ISSUE THREAD

**Issue by mmoraes-rafael** [scholarly-python-package/scholarly#158]
Hi,

The Navigator class raises an Exception [here](https://github.com/scholarly-python-package/scholarly/blob/1255f662308a1c7407db0f896086bd0902be7f7c/scholarly/_navigator.py#L129) when `tries` exceeds `self._max_retries`.
However this is too generic and makes it harder to capture at caller functions.
I suggest a custom exception is used there, such as:

```python
class MaxTriesExceededException(Exception):
    pass
```

Thanks

**Comment by ipeirotis** [comment]
Added in v1.0.5
