### ISSUE TITLE
Selenium Deprecation Warning

### ISSUE THREAD

**Issue by programize-admin** [scholarly-python-package/scholarly#160]
The way a user can pass capabilities to the Selenium webdriver has changed. This results in the following error:
` self._webdriver = webdriver.Firefox(desired_capabilities = caps)
/usr/lib/python3.8/site-packages/cryptography/x509/general_name.py:155: ResourceWarning: unclosed <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 38350), raddr=('127.0.0.1', 56205)>
  instance._value = value
ResourceWarning: Enable tracemalloc to get the object allocation traceback
./scholarly/_navigator.py:85: DeprecationWarning: capabilities and desired_capabilities have been deprecated, please pass in a Service object
  self._webdriver = webdriver.Firefox(desired_capabilities = caps)`

#### Steps to reproduce:
- Launch a scholarly connection that uses Proxy.
- Get a captcha request.
- The above deprecation warning should be displayed, while executing the `_get_webdriver()` method of `Navigator` class.

#### Solution:
According to the Selenium documentation, this is the recommended way to set HTTP proxies to the webdriver, as of the most recent version of Selenium:
https://www.selenium.dev/documentation/en/webdriver/http_proxies/

**Comment by ipeirotis** [comment]
Fixed in v.1.0.3
