### ISSUE TITLE
Disable scholar.log

### ISSUE THREAD

**Issue by jacksongoode** [scholarly-python-package/scholarly#171]
The log file created often becomes quite large and unnecessary in production. Is there a way to disable the generation of the file?

**Comment by silvavn** [comment]
Currently, you would have to disable it on your local scholarly. I will mark this as an improvement.

**Comment by dsatfire** [comment]
This is a bug not an enhancement. Libraries shouldn't attempt to control logging outputs/handlers. Those should be configured by the user.  Even if I were to disable the logger from my calling script, it doesn't prevent this module from creating the log file on import. 
Think about the situation where the dependencies of this module auto-create a log file on import. Your project root directory would be full of dependency logs.

**Comment by jacksonmgoode** [comment]
I also don't think this should have been enabled by default. It's file size can get quite large and there is not warning on the user's behalf.

**Comment by ipeirotis** [comment]
Fixed in v1.0
