### ISSUE TITLE
Error when running scholarly

### ISSUE THREAD

**Issue by evertonrsc** [scholarly-python-package/scholarly#178]
When trying to run the simple example shown at README

`from scholarly import scholarly`
`print(next(scholarly.search_author('Steven A. Cholewiak')))`

an error is reported from line 122 in __navigator.py:

`File "/.../Library/Python/3.7/lib/python/site-packages/scholarly/_navigator.py", line 122, in _close_session
    if self._webdriver:
AttributeError: 'Navigator' object has no attribute '_webdriver'`

**Comment by ipeirotis** [comment]
Just tried to replicate this after installing the latest version (` pip3 install -U pip scholarly`). I could not replicate the problem.
