### ISSUE TITLE
[Enhancement] Add publication limit parameter for retrieving author objects

### ISSUE THREAD

**Issue by mzhukovs** [scholarly-python-package/scholarly#181]
Some authors take a very long time to retrieve results for due to their having many publications - it would be convenient to be able to pass a parameter that limits how many publication objects we want in the returned Author object.

If there is already a way to do this, please let me know, and thanks for the great library.

**Comment by ipeirotis** [comment]
In v.1.0.6 there is an added a `publication_limit` parameter in `fill` and in `search_author_id`

**Comment by mzhukovs** [comment]
@ipeirotis is there a reason this parameter is not included in the code in the latest version? from commit
https://github.com/scholarly-python-package/scholarly/commit/4556af464624700a50a5e42107f27038c9bc4c88
