### ISSUE TITLE
Add geckodriver install to the documentation?

### ISSUE THREAD

**Issue by JamesCraster** [scholarly-python-package/scholarly#185]
Thank you for your work on scholarly.

My problem is in accessing `pub.citedby`, all other queries/`.fill()` calls work every time; I believe this suggests Google is not blocking me.

When referring to  `pub.citedby` on OSX without Tor/a FreeProxy, geckodriver runs and launches the Google Scholar site. I am then prompted to enter a CAPTCHA, and on on successful entry I get the data. It works perfectly.

But on Ubuntu 18.04 when using `pub.citedby`, I always get the `Cannot fetch the page` exception, even if I use `use_proxy` or `use_tor`. I think this is because the browser isn't launching and so isn't displaying the CAPTCHAs on Ubuntu. I note the same happens in OSX - when using a FreeProxy `pub.citedby` fails. I would guess that this is some kind of geckodriver issue.

**Comment by JamesCraster** [comment]
In my scholarly log I get:
INFO:scholarly:Exception WebDriverException while fetching page: ("'geckodriver' executable needs to be in PATH. ",)

Do you have any docs on installing geckodriver?

**Comment by JamesCraster** [comment]
I'm getting lots of NotADirectoryErrors:

`INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=search_authors&mauthors=Richard%20Feynman
INFO:scholarly:Found 2 authors
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&user=B7vSqZsAAAAJ&pagesize=100
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&user=B7vSqZsAAAAJ&cstart=100&pagesize=100
INFO:scholarly:Getting https://scholar.google.com/citations?hl=en&view_op=view_citation&citation_for_view=B7vSqZsAAAAJ:hMod-77fHWUC
INFO:scholarly:Getting https://scholar.google.com/scholar?cites=14769952204323476283
INFO:scholarly:Got a captcha request.
INFO:scholarly:Exception NotADirectoryError while fetching page: (20, 'Not a directory')
INFO:scholarly:Retrying with a new session.
INFO:scholarly:Got a captcha request.
INFO:scholarly:Exception NotADirectoryError while fetching page: (20, 'Not a directory')
INFO:scholarly:Retrying with a new session.
INFO:scholarly:Got a captcha request.
INFO:scholarly:Exception NotADirectoryError while fetching page: (20, 'Not a directory')
INFO:scholarly:Retrying with a new session.
INFO:scholarly:Got a captcha request.
INFO:scholarly:Exception NotADirectoryError while fetching page: (20, 'Not a directory')
INFO:scholarly:Retrying with a new session.
INFO:scholarly:Got a captcha request.
INFO:scholarly:Exception NotADirectoryError while fetching page: (20, 'Not a directory')
INFO:scholarly:Retrying with a new session.`

But when it says 'got a captcha request', I have no opportunity to fill the captcha in. The firefox page does not appear. In addition, this behaviour exists with Tor and proxies also.

**The problem is in brief:** how do I get the CAPTCHAs to load?

**Comment by CinnyLin** [comment]
Hi @JamesCraster !! I filed issue #211 and @a1png kindly suggested me a possible solution, which is very similar to what you are describing here. I installed geckodriver and moved it to usr/bin on my Mac but now I am getting a new error because it seems that geckodriver does not work on Mac now. The error I am getting is `INFO:scholarly:Exception SessionNotCreatedException while fetching page: ("Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line", None, None)` as directly copying from the log file. I was wondering how you made it work? Thank you so much!

**Comment by a1png** [comment]
@CinnyLin You need to install firefox on your mac, or install something called [chrome drive](https://www.google.com/search?q=chromedrive&oq=chromedrive&aqs=chrome..69i57j0l6j69i60.1647j0j7&sourceid=chrome&ie=UTF-8) change the line `self._webdriver = webdriver.Firefox()` to `self._webdriver = webdriver.Chrome("PATH_TO_YOUR_CHROME_DRIVER")`

**Comment by JamesCraster** [comment]
@CinnyLin When I was talking about /usr/bin I was talking about on my Ubuntu 18.04 system. I don't have any input on your OSX issue unfortunately. I think some further docs on webdriver could be useful.

**Comment by ipeirotis** [comment]
Merging this with https://github.com/scholarly-python-package/scholarly/issues/89
