### ISSUE TITLE
search_pubs failed with " Exception: Cannot fetch the page from Google Scholar."

### ISSUE THREAD

**Issue by Jianbin-IBM** [scholarly-python-package/scholarly#188]
Hi,
This is a very useful repo! Thanks very much!

I tried search_author. It works well. But when I tried: search_pubs, it worked for a moment. Then it always returned: " Exception: Cannot fetch the page from Google Scholar." I got same message when I try unit test for test_search_pubs_filling_publication_contents(self)

I also tried to use set proxy, no luck for search_pubs. 

Any clues here? Thanks!

**Comment by mebibou** [comment]
you are just blocked from Google that is all

**Comment by mguidoti** [comment]
Hi, 

Just reporting: it happened to me too after just one query.

Best,

**Comment by maitchison** [comment]
Me too :(

**Comment by ipeirotis** [comment]
Since this is a Google Scholar blocking issue, it needs to be dealt with proper proxying and/or handling of captchas.
