### ISSUE TITLE
Search by Author Google Scholar URL instead of Name

### ISSUE THREAD

**Issue by jonsaadfalcon** [scholarly-python-package/scholarly#192]
Hello, I was wondering if there is a method within scholarly for searching an author by their Google Scholar URL instead of their name. It seems that when I search up their name, I sometimes get the wrong individual. Thank you

**Comment by ipeirotis** [comment]
You can use the `search_author_id` function t search by author id. (From what I see, the function is not yet in the documentation, but it is there.)

**Comment by ipeirotis** [comment]
Fixed in v0.5
