### ISSUE TITLE
Can't Serialize Publication Object

### ISSUE THREAD

**Issue by samjett247** [scholarly-python-package/scholarly#195]
Thank you for building this tool :) 

I'm using Scholarly for a large scale data analysis project, and I'm struggling to serialize any of the Publication objects into json format. I can (and am) working on some backdoor ways to serialize the publication objects, but would be much cleaner for this sort of thing if the objects exposed a `toJson()` method or similar for serialization purposes. Or, maybe there is a better way to do serialization, and I just haven't found it yet?

**Comment by silvavn** [comment]
@samjett247 the publication and author are actually dicts. You can dump them using the json python package. Otherwise you could dump the class dictionaries. We would be also open for a PR for the `toJson()` method

**Comment by ipeirotis** [comment]
Following up on @silvavn: Here is a piece of code that materializes both the Author and Publication objects:
https://github.com/ipeirotis/scholar_update/blob/master/fetch_pubs.py

You need to delete a few fields that are not serializable, but it is not a big deal.

In the next iteration of scholarly, we aim at making the Author and Publication objects pure data containers, that are directly serializable.

**Comment by samjett247** [comment]
Perfect, thanks for the help. Closing issue.
