### ISSUE TITLE
scholarly:Exception TypeError while fetching page: ("create_cookie() got unexpected keyword arguments: ['sameSite']",)

### ISSUE THREAD

**Issue by stevensgeek41** [scholarly-python-package/scholarly#196]
I was using scholarly on windows 10. I installed firefox and geckodriver, and can initiate the firefox session successfully, yet after I got the captha right, the program keeps create new session. I looked into the scholarly log, found this below:
INFO:scholarly:Getting https://scholar.google.com/scholar?hl=en&q=Spatial-Temporal%20Synchronous%20Graph%20Convolutional%20Networks%3A%20A%20New%20Framework%20for%20Spatial-Temporal%20Network%20Data%20Forecasting&as_vis=0&as_sdt=0,33
INFO:scholarly:Session proxy config is {}
INFO:scholarly:Got a captcha request.
INFO:scholarly:Solving the captcha took already 10 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 20 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 30 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 40 seconds (of maximum 604800 s).
INFO:scholarly:Solved captcha in less than 50 seconds.
INFO:scholarly:Exception TypeError while fetching page: ("create_cookie() got unexpected keyword arguments: ['sameSite']",)
INFO:scholarly:Retrying with a new session.
INFO:scholarly:Session proxy config is {}
INFO:scholarly:Got a captcha request.
INFO:scholarly:Solving the captcha took already 10 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 20 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 30 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 40 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 50 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 60 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 70 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 80 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 90 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 100 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 110 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 120 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 130 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 140 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 150 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 160 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 170 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 180 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 190 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 200 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 210 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 220 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 230 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 240 seconds (of maximum 604800 s).
INFO:scholarly:Getting https://scholar.google.com/scholar?hl=en&q=Spatial-Temporal%20Synchronous%20Graph%20Convolutional%20Networks%3A%20A%20New%20Framework%20for%20Spatial-Temporal%20Network%20Data%20Forecasting&as_vis=0&as_sdt=0,33
INFO:scholarly:Session proxy config is {}
INFO:scholarly:Got a captcha request.
INFO:scholarly:Solving the captcha took already 10 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 20 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 30 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 40 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 50 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 60 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 70 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 80 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 90 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 100 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 110 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 120 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 130 seconds (of maximum 604800 s).
INFO:scholarly:Solved captcha in less than 140 seconds.
INFO:scholarly:Exception TypeError while fetching page: ("create_cookie() got unexpected keyword arguments: ['sameSite']",)
INFO:scholarly:Retrying with a new session.
INFO:scholarly:Session proxy config is {}
INFO:scholarly:Got a captcha request.
INFO:scholarly:Solving the captcha took already 10 seconds (of maximum 604800 s).
INFO:scholarly:Solving the captcha took already 20 seconds (of maximum 604800 s).

I think it's due to the mis use of create_cookie(). I'm using a python version 3.8.3.

**Comment by stevensgeek41** [comment]
To reproduce the issue, use scholarly.search_pubs method

**Comment by ac-jorellanaf** [comment]
I encountered the same problem. It seems the `requests.cookies.create_cookie()` method does not accept the field `'sameSite'`, which is set by Google after doing the captcha. I found a quick workaround, which is to pop that field from the cookie object before setting in the file `_proxy_generator.py`.

In essence, add the line
`cookie.pop("sameSite", None)`
below line 352 in `_proxy_generator.py`.

**Comment by ipeirotis** [comment]
Merging this with https://github.com/scholarly-python-package/scholarly/issues/89

**Comment by jonasengelmann** [comment]
It seems like this fix was never merged! I still have to manually pop the sameSite cookie!

**Comment by ipeirotis** [comment]
Please proceed with a pull request with the fix.

**Comment by arunkannawadi** [comment]
Fixed in #457
