### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by cayekple** [scholarly-python-package/scholarly#197]
full_pub = pub.fill()
  File "/usr/local/lib/python3.8/site-packages/scholarly/publication.py", line 262, in fill
    if abstract.text[0:8].lower() == 'abstract':
AttributeError: 'NoneType' object has no attribute 'text'

This error can be reproduced with the following code

```
search_author_by_name = scholarly.search_author('LK Sam-Amoah')
author = next(search_author_by_name).fill()
for pub in author.publications:
                full_pub = pub.fill()
```

**Comment by ipeirotis** [comment]
Fixed in the latest version.
