### ISSUE TITLE
search_pubs() result size limited to 1000

### ISSUE THREAD

**Issue by samjett247** [scholarly-python-package/scholarly#198]
I've noticed that, when I search for a general topic that has more than 1000 results associated with it, the generator ends at 1000. I'm wondering if this is a restriction on the google scholar side of things or if anyone else has noticed this issue.

**Comment by ipeirotis** [comment]
That is the limit of the number of publications returned by Google Scholar

**Comment by hp0404** [comment]
Just to clarify, we can't get more than 1k results and that's can't be fixed, so the only options we have are to use `year_high`, `year_low` filters, and to tailor the query to be more precise?

**Comment by ipeirotis** [comment]
Scholarly operates on top of Google Scholar's web interface. If you can get it by searching the web, you can get it from scholarly. If it is not possible to get it from the web, then you cannot get it from scholarly either.
