### ISSUE TITLE
Problem with ProxyGenerator

### ISSUE THREAD

**Issue by sdspieg** [scholarly-python-package/scholarly#200]
When I follow the instructions for it ("from scholarly import ProxyGenerator", I get the following error: ImportError: cannot import name 'ProxyGenerator' from 'scholarly' (C:\[path]\scholarly\lib\site-packages\scholarly\__init__.py). 
And I appear not to be the only one - see [here](https://stackoverflow.com/questions/63943438/cant-install-proxygenerator-from-scholary). Could there be a step missing in the installation/documentation?

**Comment by ipeirotis** [comment]
Make sure that you use the latest version:

I just executed the following code on Colab without issues:

```
!pip3 install -U pip scholarly
```

and then

```python
from scholarly import scholarly,  ProxyGenerator
pg = ProxyGenerator()

proxy = '......'
pg.SingleProxy(http = proxy, https = proxy)
scholarly.use_proxy(pg)

search_query = scholarly.search_author('Steven A Cholewiak')
author = next(search_query).fill()
print(author)
```
