### ISSUE TITLE
How to export results in json format

### ISSUE THREAD

**Issue by sdspieg** [scholarly-python-package/scholarly#201]
Sorry for this basic question, but how do we export our results? Scholarly works great when I follow the examples but use the queries I am interested in. I can display a few items through print(next(search_query)). But how can we export that as a json file? And also is there a way to specify how many items we want to export, e.g.if we want to export - say - the first 500 hits? I'm sure this may be obvious to many, but it is not to me (and presumably not to me alone :). So adding a few examples for that in the documentation would be great. Thanks much!

**Comment by ipeirotis** [comment]
Not a basic question :)

You can see the discussion at https://github.com/scholarly-python-package/scholarly/issues/195 and a pointer to some code that I have written to save scholar results in JSON.

We are also working on cleaning up the code and making export to JSON easier and more straightforward.
