### ISSUE TITLE
Cannot fetch the page from Google Scholar.

### ISSUE THREAD

**Issue by aalbas** [scholarly-python-package/scholarly#205]
search_pubs basically always returns Cannot fetch the page from Google Scholar. exception even on the examples

**Comment by JaniceXiong** [comment]
Do you fix this problem?

**Comment by ipeirotis** [comment]
The "Cannot fetch the page from Google Scholar" is not a bug, it is a standard behavior by Google Scholar and means that the IP that you are using has been blocked by Google.

Please use proxies, paid if necessary.
