### ISSUE TITLE
Does anybody have a functioning Google colab for this?

### ISSUE THREAD

**Issue by sdspieg** [scholarly-python-package/scholarly#209]
I suspect one of the most typical use cases for Scholarly is to allow scholars to enter a (hopefully also advanced, but probably primarily keyword-based) search on Google Scholar and to then be able to scrape the results and then export those into something like a CSV- or JSON-file. It seems like Scholarly already has most if not all of that functionality (including the ProxyGenerator). But does somebody have a Google Colab notebook that goes through all the steps that are required? And incidentally, if somebody does have one and is willing to share it, our team would be more than willing to help to document that in the Colab itself or on https://scholarly.readthedocs.io.

**Comment by ipeirotis** [comment]
https://colab.research.google.com/drive/1kkrSvC3f9RisGpgHZ2ryx5F0SOaxHocg?usp=sharing

**Comment by ipeirotis** [comment]
The current version of scholarly returns pure `dict`s as results, and it should be trivially easy to save the results as JSON, using a simple `json.dumps(author)` and `json.dumps(pub)`

I assume the current documentation is showing all the necessary steps, but if you would like to see anything more, let us know.

For most of the work on Colaboratory, you are likely to need a proxy server for fetching publications, as Google Scholar tends to block quickly any publication search requests.
