### ISSUE TITLE
Exception: Cannot fetch the page from Google Scholar.

### ISSUE THREAD

**Issue by Gautamshahi** [scholarly-python-package/scholarly#210]
Hi,

I tried all possible way, but still, I am getting the **error Exception: Cannot fetch the page from Google Scholar**

Is there a latest trick to solve the error?

**Comment by ipeirotis** [comment]
Perhaps use proxies.

Default setting seems to run perfectly fine on Colab:

https://colab.research.google.com/drive/1kkrSvC3f9RisGpgHZ2ryx5F0SOaxHocg?usp=sharing
