### ISSUE TITLE
"Exception: Cannot fetch the page from Google Scholar." for "citedby" attribute in Publication module

### ISSUE THREAD

**Issue by CinnyLin** [scholarly-python-package/scholarly#211]
When I try to run `[citation.bib['title'] for citation in pub.citedby]`, it returns the error message: `"Exception: Cannot fetch the page from Google Scholar."` I am following the example on the [documentation page](https://pypi.org/project/scholarly/).

**Comment by crunchpaste** [comment]
Could confirm the same happens. The usage section on [readthedocs.io](https://scholarly.readthedocs.io/en/latest/quickstart.html#usage) suggests `citation.bib['title'] for citation in pub.get_citedby()` should be used, but that just gives me `'Publication' object has no attribute 'get_citedby'`.

**Comment by ritesh007sharma** [comment]
I am getting the same issue as well. I tried using FreeProxies which did not work as expected.
I am currently using Tor, I configured my Mac to use Tor, my browsers seems to be using Tor and works fine but I am still getting the same error while trying to fetch data. 
Am I missing something?

**Comment by a1png** [comment]
I also had this problem.
After looking into the code and turning on the logging in _navigator.py, I found the actual error is:
`INFO:scholarly:Exception WebDriverException while fetching page: ("'geckodriver' executable needs to be in PATH. ",)`
Configuring geckodriver with Selenium correctly will get it work.
For simplicity, I just put that geckdriver executable in the working dir and it works

**Comment by CinnyLin** [comment]
I also tried using the free proxy and still had the error. @a1png can you explain in more detail how you worked around the error? do you mind sharing the code maybe? I would really really love to figure this out. Thank you so much!!

**Comment by a1png** [comment]
@CinnyLin If you look into the log file in the working directory, which is `scholar.log`, or turn on logging in command line tool by removing the `filename` parameter in `logging.basicConfig(filename='scholar.log', level=logging.INFO)` in `_navigator.py` in the library, you will be able to see the actual reason of this error.
In my case, the actual error was that Selenium, a library that this lirary depends on, need a dependency called 'geckodriver', all you need to do is to configure it to run with Selenium. See [here](https://www.edureka.co/blog/selenium-chromedriver-and-geckodriver).  I put the geckodriver executable, which can be found [here](https://github.com/mozilla/geckodriver/releases), in my work dir and it worked for me.

**Comment by CinnyLin** [comment]
@a1png Thank you so much!! I followed your steps, checking my logs, downloading geckodriver and changing its path to executable. But according to the [documentation](https://firefox-source-docs.mozilla.org/testing/geckodriver/Notarization.html), geckodriver doesn't work for macOS right now. 

I tried using the fix they proposed on the doc and received another error. I checked the log file and it seems that it is another error from Selenium, `Exception SessionNotCreatedException while fetching page: ("Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line", None, None)`. I couldn't really find the solution for this error on Google but thank you so much for your help until this point!!

**Comment by ipeirotis** [comment]
There is an issue for checking the build on Mac and Windows https://github.com/scholarly-python-package/scholarly/issues/89 in addition to https://github.com/scholarly-python-package/scholarly/issues/185

I will close this issue as duplicate.
