### ISSUE TITLE
How to obtain "cluster" property for Publication object?

### ISSUE THREAD

**Issue by sebastian-lapuschkin-sideprojects** [scholarly-python-package/scholarly#213]
Is there any way to obtain the unique paper / cluster id for a Publication object using scholarly, i.e. as in this link:
https://scholar.google.com/scholar?cluster=15321553275576339397

and described/linked here:
https://www.wikidata.org/wiki/Property:P4028

I noticed that the same publication id extracted from two co-authors is not unique.

**Comment by ipeirotis** [comment]
Planned for version 1.0. Just wait a couple of weeks and we should have this out.

**Comment by sebastian-lapuschkin-sideprojects** [comment]
great, thanks!

**Comment by sebastian-lapuschkin-sideprojects** [comment]
hi all, since scholarly is now at version >1.0.0, has this feature been implemented yet?
after checking some (filled) publications between myself and co-authors, it seems as if the fields/properties `cites_id` and  `citedby_url` _might_ do the trick.

could you please verify (or correct me) that above fields constitute unique identifiers _for publications_ regardless of the author they have been obtained from?

**Comment by ipeirotis** [comment]
The `cites_id` is indeed an id for a single paper. 

Sometimes, if the publication comes from a "merged" list of papers from an author's page, the "citedby_id" will be a comma-separated list of values showing the list of all the papers that were merged to create the entry.
