### ISSUE TITLE
Publication attributes are not always int()able

### ISSUE THREAD

**Issue by tyarkoni** [scholarly-python-package/scholarly#227]
Currently, when filling in publications, scholarly attempts to convert the volume and issue fields to integers. This seems reasonable at first glance, but articles in GS *can* have strings in the volume and issue fields, in which case the conversion fails and an exception is raised. I just ran into this problem with an article that had the issue "`3-4`". I solved the problem by editing the original entry, but this will not generally be possible in cases where people don't own the articles in question.

I'm not sure if you want to address this explicitly (e.g., via a class-level configuration option, or by defaulting to using strings everywhere), but am flagging it here just so that there's a record that this is a known issue. Feel free to close if you don't plan to fix it—I can't imagine it arises very often.

**Comment by ceriottm** [comment]
Same issue here. Edited the source to remove int(), I think one cannot make assumptions like these. 
E.g. I have seen Phys. Rev. particles with volume "B1234" and similar

**Comment by ipeirotis** [comment]
Fixed in v1.0.2
