### ISSUE TITLE
[Enhancement] search_pubs result size limit

### ISSUE THREAD

**Issue by hp0404** [scholarly-python-package/scholarly#232]
Is it possible to go over the 1000 items limit with `scholarly.search_pubs()`? 

For example, `deterrence` has around 547k results which go way over 1k results that scholarly yields, and is accessible through scholar's site (`?start=` param is incremented by 10 for every next page, it seems). 

I could try changing the source code if you help me navigate (where is this behavior regarding size limit defined?) :)

**Comment by ipeirotis** [comment]
Google does not return more than 1000 results. You can verify that by going through all the pages.
