### ISSUE TITLE
how to get an http proxy?

### ISSUE THREAD

**Issue by IbtihalFerwana** [scholarly-python-package/scholarly#234]
Hello, 

I do not know much about setting a proxy, any hints in this regards?
I'm using jupyter notebook, local host, and windows machine. Where should I get an http proxy?

**Comment by ipeirotis** [comment]
You can signup for a service like https://luminati.io/ or you can use the FreeProxies, as described [in the documentation](https://github.com/scholarly-python-package/scholarly#using-proxies)
