### ISSUE TITLE
Getting coauthors from the publication list

### ISSUE THREAD

**Issue by nd7141** [scholarly-python-package/scholarly#243]
If I query an author: 

```
myid = '2Q8ksBgAAAAJ'
author = scholarly.search_author_id(myid, filled=True)
print(author['publications'])
```
I get the list of publications, where the authors are presented as plain names. It would be great in addition to this append information about author_ids for each publication. 

Otherwise, I need to query each publication and retrieve the author_ids, which becomes extremely long: 
```
author = scholarly.search_author_id(myid, filled=True)
pubs = []
author['coauthor_ids'] = []
for pub in author.get('publications', []):
    title = pub['bib']['title']
    found_pub = next(scholarly.search_pubs(title)) # this is proxy (need to find better way search for publications)
    coauthor_ids = found_pub['author_id']
    next_ids += [id for id in coauthor_ids if id not in visited and id]
    author['coauthor_ids'].append(coauthor_ids)
    pubs.append(pub)
```

Is getting coauthors for a scholar possible in a single query?

**Comment by ipeirotis** [comment]
The coauthor ids are not available for publications that come from the author page, as there is no such link information.
