### ISSUE TITLE
Searching by publication id

### ISSUE THREAD

**Issue by nd7141** [scholarly-python-package/scholarly#244]
Is it possible to query, not by publication title, but by publication id? 

For example, from a list of author's publications I get the field `author_pub_id`, which combines author_id and publication_id. Is it possible to use then this publication_id for the search?

**Comment by ipeirotis** [comment]
You can just do a `scholarly.fill(p)` (with `p` being the publication object) and you will get back the filled publication.

For example, something like the code below:

```python

author = next(scholarly.search_author('foster provost'))
author = scholarly.fill(author)
top_ten_pubs = author['publications'][:10]
for p in top_ten_pubs:
  scholarly.fill(p)

for p in top_ten_pubs:
  scholarly.pprint(p)
  print("\n\n-------\n\n")
```

**Comment by nd7141** [comment]
But I asked about a different thing. My question if it's possible to query by publication_id? Because when I query by publication_title I get a list of publications, which I don't want later to process.

**Comment by ipeirotis** [comment]
Searching using publication id will return the author page of the publication, with all the elements that you see.

For example, when you search for the publication id `-Km63D4AAAAJ:u5HHmVD_uO8C` you use the URL

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=-Km63D4AAAAJ&citation_for_view=-Km63D4AAAAJ:u5HHmVD_uO8C&tzom=300

and you get back the parsed publication object 

```
{'author_pub_id': '-Km63D4AAAAJ:u5HHmVD_uO8C',
 'bib': {'abstract': 'In real-world environments it usually is difficult to '
                     'specify target operating conditions precisely, for '
                     'example, target misclassification costs. This '
                     'uncertainty makes building robust classification systems '
                     'problematic. We show that it is possible to build a '
                     'hybrid classifier that will perform at least as well as '
                     'the best available classifier for any target conditions. '
                     'In some cases, the performance of the hybrid actually '
                     'can surpass that of the best known classifier. This '
                     'robust performance extends across a wide variety of '
                     'comparison frameworks, including the optimization of '
                     'metrics such as accuracy, expected cost, lift, '
                     'precision, recall, and workforce utilization. The hybrid '
                     'also is efficient to build, to store, and to update. The '
                     'hybrid is based on a method for the comparison of '
                     'classifier performance that is robust to imprecise class '
                     'distributions and misclassification costs. The ROC '
                     'convex hull (ROCCH) method combines …',
         'author': 'Foster Provost and Tom Fawcett',
         'journal': 'Machine learning',
         'number': '3',
         'pages': '203-231',
         'pub_year': '2001',
         'publisher': 'Kluwer Academic Publishers',
         'title': 'Robust classification for imprecise environments',
         'volume': '42'},
 'citedby_url': '/scholar?cites=17970352882167184968',
 'cites_id': '17970352882167184968',
 'cites_per_year': {2001: 23,
                    2002: 34,
                    2003: 64,
                    2004: 65,
                    2005: 74,
                    2006: 98,
                    2007: 110,
                    2008: 121,
                    2009: 83,
                    2010: 104,
                    2011: 72,
                    2012: 63,
                    2013: 76,
                    2014: 88,
                    2015: 71,
                    2016: 67,
                    2017: 62,
                    2018: 67,
                    2019: 62,
                    2020: 79},
 'eprint_url': 'https://link.springer.com/content/pdf/10.1023/A:1007601015854.pdf',
 'filled': True,
 'num_citations': 1510,
 'pub_url': 'https://link.springer.com/article/10.1023/A:1007601015854',
 'source': 'AUTHOR_PUBLICATION_ENTRY'}

```

It seems that you want to do something else, though, but I do not quite understand what.

**Comment by ligon** [comment]
I have really the same request as @nd7141.  At present with an *author* id I can use, e.g., `scholarly.search_author_id('jRwNfxwAAAAJ')` (and perhaps subsequently use fill) to learn what there is to learn about that author.  

I'm surprised that there's not an analogous method along the lines of `scholarly.search_pub_id('u5HHmVD_uO8C')`.    Ideally this would parse the information from https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=u5HHmVD_uO8C.  

At present one can feed urls of the above form into `scholarly.search_pubs_custom_url()`, but the parser breaks.

The custom url solution you offer above *does* work, but requires knowledge not only of the publication id, but also the author id of at least one of the authors.
