### ISSUE TITLE
Function bibtex() doesn't work

### ISSUE THREAD

**Issue by OneMoreRandomGuy** [scholarly-python-package/scholarly#245]
I've tested this function with a publication fill and without it and it doesnt work in any way.

Output data give me a KEYERROR: 'ENTRYTYPE'

I dont know if I'm using the function correctly. I'm calling it 'scholarly.bibtex(author['publications'][0]'.

Thanks!

**Comment by ipeirotis** [comment]
Please provide example code that generated the issue

**Comment by OneMoreRandomGuy** [comment]
``` search_query = scholarly.search_author('Steven A. Cholewiak')
author = scholarly.fill(next(search_query))

pub = author['publications'][0]

print(scholarly.bibtex(pub)
```

I tried it with the publications filled too.

```
pub = scholarly.fill(author['publications'][0])

print(scholarly.bibtex(pub)
```

**Comment by OneMoreRandomGuy** [comment]
I was just testing with search_pubs. I had not viewed the page and how it give the information.

If i wanted to take bibtex of a publication of an author, i should take name from author['publications'[n]['bib']['title'] and make a search_pubs of it.

That was my error. Sorry for waste your time.

Closing.
