### ISSUE TITLE
Behavior of tor when using Internal vs. External

### ISSUE THREAD

**Issue by jacksongoode** [scholarly-python-package/scholarly#249]
It is not totally clear the difference between the Internal or External functions when loading Tor as a backend. I've attempted to use both, however, it seems that there is some issue with killing the tor process at the end of the Internal usage. At least on Ubuntu this doesn't appear to throw an error as it did on macOS but I haven't tried 1.0 on the Mac.

I believe some more documentation may be needed on how tor is launched and handled, restarted in the context of a program for each method.

**Comment by jacksongoode** [comment]
I am also curious about the MaxTriesExceededException. I'm guessing there is a limit set to Tor's attempts, but is this after refreshing the relay or the max tries of a single relay - and tor is unable to refresh?

**Comment by ipeirotis** [comment]
Internal Tor is using a python package for launching a Tor client.

External Tor is a separate Tor server. It behaves mostly like an ordinary proxy, but with the ability to ask the Tor server to refresh and get a new exit node. We always ask for a new node when we detect a problem with Google Scholar blocking the network request.

The MaxRetries is mostly independent of Tor and is related to how many consecutive errors we observe. By default, when we ask immediately for a refresh when we detect an error.

**Comment by jacksongoode** [comment]
> Internal Tor is using a python package for launching a Tor client.
> 
> External Tor is a separate Tor server. It behaves mostly like an ordinary proxy, but with the ability to ask the Tor server to refresh and get a new exit node. We always ask for a new node when we detect a problem with Google Scholar blocking the network request.
> 
> The MaxRetries is mostly independent of Tor and is related to how many consecutive errors we observe. By default, when we ask immediately for a refresh when we detect an error.

Thank you for the quick response. Is this normal behavior then to get this error intermittently in usage of both cases?

**Comment by ipeirotis** [comment]
Very common. When we used it early on, it was better but by now I think that Google has blacklisted most of the Tor exits, so Tor is not as useful as it used to be.
