### ISSUE TITLE
FreeProxies error with search_pubs()

### ISSUE THREAD

**Issue by tomasgarciaferrari** [scholarly-python-package/scholarly#260]
I am having “Cannot Fetch from Google Scholar” error.

I have tried using FreeProxy following the provided example:

`from scholarly import scholarly, ProxyGenerator`
`pg = ProxyGenerator()`
`pg.FreeProxies()`
`scholarly.use_proxy(pg)`
`author = next(scholarly.search_author('Steven A Cholewiak'))`
`scholarly.pprint(author)`

It does work with the search_author() method, but not with the search_pubs() one (but this is also the case without using FreeProxy).

Any suggestions?

**Comment by ipeirotis** [comment]
You will probably need to use another proxy as the ones from FreeProxy tend to be blocked often.
