### ISSUE TITLE
get publication's co-author names and published venue

### ISSUE THREAD

**Issue by Misty-2409** [scholarly-python-package/scholarly#264]
using the proxy generator, I have successfully found all the publication titles and their number of citations. But I cannot generate the name of co-authors and venue in addition to the publication's title. To sum up, I need all the publication names, their corresponding venue, co-author names and number of citation. something like:

publications: {title: x
                      author: [a,b,c]
                      venue: q
                      noc:12
}

How to do that? Here is a sample of my code.

`from scholarly import scholarly, ProxyGenerator

pg = ProxyGenerator()
pg.Tor_Internal(tor_cmd = "tor")
scholarly.use_proxy(pg)

search_query = scholarly.search_author('Seemanta Saha')
author_fill = next(search_query)
author = scholarly.fill(author_fill)
#print(author)

title = [pub['bib']['title'] for pub in author['publications']]
number_of_citations = [pub['num_citations'] for pub in author['publications']]`

**Comment by ipeirotis** [comment]
You need to also use the `scholarly.fill` command for each publication. Note that you can query for authors without a problem, but once you start filling publications, you will need a proxy service.

**Comment by Misty-2409** [comment]
using scholarly.fill command for each publication, I can capture the co-author list, published year etc. But I cannot capture the published venue for conference. I mean to say I can get the name of the journal but cannot get the name of the conference. The only thing that I get is the name of the publisher (IEEE) for a conference. I tried to use a loop for searching each of the publications through search_pubs(). But I cannot get result more than three publications.

Is there any other way?

**Comment by ipeirotis** [comment]
You will need to use a proxy, most likely.
