### ISSUE TITLE
Cannot fetch the page from Google Scholar

### ISSUE THREAD

**Issue by PedroTayer** [scholarly-python-package/scholarly#279]
Hi!

[windows user]

I can't fetch data from google scholar anymore, I've tried freeproxy, both Tor Internal and External and Luminati. Spent the last two days on this I couldn't manage to solve so I'm here.

I can manage to open correctly a TOR session but when I try to query search_pubs the exception 'Cannot fetch the page from Google Scholar' raises from navigator on command 'get_page'.

My `torcc `is configured as: 

```
ClientOnionAuthDir C:\Tor Browser\Browser\TorBrowser\Data\Tor\onion-auth
DataDirectory C:\Tor Browser\Browser\TorBrowser\Data\Tor
GeoIPFile C:\Tor Browser\Browser\TorBrowser\Data\Tor\geoip
GeoIPv6File C:\Tor Browser\Browser\TorBrowser\Data\Tor\geoip6

ControlPort 9051
CookieAuthentication 1
HashedControlPassword 16:9BA0583BA487ECF360C83CB96C06XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

This has password I've created using `tor --hash-password "mypass" | more`

Both ports 9050 and 9051 are 'LISTENING' when checked via cmd.

My code examples is now as follows:

```
pg = ProxyGenerator()
pg.Tor_External(tor_sock_port=9050, tor_control_port=9051, tor_password="mypass")
scholarly.use_proxy(pg)
search_query = scholarly.search_pubs('"test query"+"cast iron"')
```

My scholar.log returns a repetition of the lines above.

> DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0046)
> INFO:stem:Error while receiving a control message (SocketClosed): received exception "[WinError 10038] An operation was attempted on something that is not a socket"
> INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file".

To verify if the tor was correct, I've tested it via:

```
def get_tor_session():
    session = requests.session()
    # Tor uses the 9050 port as the default socks port
    session.proxies = {'http':  'socks5://127.0.0.1:9050',
                       'https': 'socks5://127.0.0.1:9050'}
    return session

# Make a request through the Tor connection
# IP visible through Tor
session = get_tor_session()
print('Congratulations' in session.get('http://check.torproject.org/').text)
```
And it returns Congratulations

Somebody can help me fixing this?

Is there any active way I can get the data without being blocked?

Thanks

**Comment by ipeirotis** [comment]
Unfortunately, FreeProxies and Tor have been increasingly unreliable. They worked reasonably well before adding them to the official releases, but now they are effectively useless. We may actually remove these from future versions of scholarly.

Check if you can run the `search_author` request? If that works, then it is really a matter of Google being super strict with the searching of publications. You will need to space out your requests and use other proxy services.

FYI, I just tried running your code on Colab, using Luminati:

```python
from scholarly import scholarly, ProxyGenerator

pg = ProxyGenerator()
pg.Luminati(usr= "....",passwd ="....", proxy_port  = "22225")
scholarly.use_proxy(pg)

search_query = scholarly.search_pubs('"test query"+"cast iron"')
r = next(search_query)
scholarly.pprint(r)
```

and it run without problems, returning this back:

```
{'author_id': ['35ESlEcAAAAJ'],
 'bib': {'abstract': 'Page 1. GEOINTERPRET: AN ONTOLOGICAL ENGINEERING '
                     'METHODOLOGY FOR AUTOMATED INTERPRETATION OF GEOSPATIAL '
                     'QUERIES by Ratchata Peachavanish BS, University of '
                     'Washington, 1995 MS, Syracuse University, 1999',
         'author': ['R Peachavanish'],
         'pub_year': '2005',
         'title': 'GeoInterpret: an ontological engineering methodology for '
                  'automated interpretation of geospatial queries',
         'venue': 'NA'},
 'citedby_url': '/scholar?cites=2262868338712386775&as_sdt=5,33&sciodt=0,33&hl=en',
 'eprint_url': 'http://d-scholarship.pitt.edu/10353/1/Peachavanish_DEC-2004.pdf',
 'filled': False,
 'gsrank': 1,
 'num_citations': 2,
 'pub_url': 'http://d-scholarship.pitt.edu/10353/',
 'source': 'PUBLICATION_SEARCH_SNIPPET',
 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3D%2522test%2Bquery%2522%252B%2522cast%2Biron%2522%26hl%3Den%26as_sdt%3D0,33&citilm=1&json=&update_op=library_add&info=1xxuzsNSZx8J&ei=hVtaYOj2L5-R6rQPjIKg4AQ',
 'url_related_articles': '/scholar?q=related:1xxuzsNSZx8J:scholar.google.com/&scioq=%22test+query%22%2B%22cast+iron%22&hl=en&as_sdt=0,33',
 'url_scholarbib': '/scholar?q=info:1xxuzsNSZx8J:scholar.google.com/&output=cite&scirp=0&hl=en'}
```
