### ISSUE TITLE
Scholar creates empty log file

### ISSUE THREAD

**Issue by ipeirotis** [scholarly-python-package/scholarly#283]
See https://github.com/scholarly-python-package/scholarly/discussions/280

**Comment by andres-fr** [comment]
Hi! 

And thanks for the great lib. Regarding the linked issues, I agree that a library shouldn't claim control of the user's filesystem. This not only can be inconvenient/annoying, but could also cause real trouble e.g. when running on locations with restricted permissions. I think logging files should be opt-in, and the user should be able to specify the location. This can be achieved as follows:

> if no location is given, don't log (default). If a location is explicitly given, try to log there, and warn/crash if there are any issues with that location.

Interestingly, the analogous Python library for the Scopus database had this exact problem. I just made a PR there with a similar opt-in rationale, you can find it here: https://github.com/ElsevierDev/elsapy/pull/65). If this approach is welcome I can propose a similar PR here.

In the meantime, here is a quick workaround: 

1. Locate the `filename="scholar.log" line at the [_proxy_generator.py](https://github.com/scholarly-python-package/scholarly/blob/master/scholarly/_proxy_generator.py) and [_navigator.py](https://github.com/scholarly-python-package/scholarly/blob/master/scholarly/_navigator.py) files.

2. Remove it :)

That seems to work just fine. As for real workarounds, I think the lib could provide a function like this (untested):

```python
def log_to_file(abspath, logger_names=None):
    """
    """
    logging.basicConfig(filename=abspath)
```

The user could then call `scholarly.log_to_file("some/path.log")`. The only potential issue I see with this is that maybe once a logger is created, basisConfig won't alter it? Anyone knows about this?

Cheers,  
Andres

**Comment by arunkannawadi** [comment]
Is this still an issue? AFAIK, `scholarly` by itself does not create a log file, but I have seen `geckodriver` does, and the latter is outside of the scope.

**Comment by andres-fr** [comment]
I don't think it is, just tested it with `scholarly==1.4.5` and no file was generated.
Furthermore, I don't know about `geckodriver` but the lines that I referred to in my previous comment can't be found anymore in master, so I assume this was specifically fixed.

Feel free to close!

**Comment by arunkannawadi** [comment]
Great, thanks for confirming. Closing the issue.
