### ISSUE TITLE
Failure to work with Scraper API

### ISSUE THREAD

**Issue by kjk11** [scholarly-python-package/scholarly#293]
I need to process several hundreds of queries with scholary. Due to the limitations of using my real IP address as well as connecting over Tor or a free proxy, I have started using the Scraper API service. My API key is active and I can curl pages from google scholar without a problem. However, when I use the Scraper API feature which has been integrated into scholarly to try and extract a bibtex citation, it nonetheless keeps throwing up a maximum tries exception. I run the latest version installed with pip3.

Sample code: 
 

```
from scraper_api import ScraperAPIClient
from scholarly import scholarly, ProxyGenerator 
pg = ProxyGenerator()
pg.ScraperAPI('api key')
scholarly.use_proxy(pg)
searchterm = "epistemic logic"
query = scholarly.search_pubs(searchterm)
pub = next(query)
bibtex = scholarly.bibtex(pub)
print(bibtex)
```

Error message:

```
query = scholarly.search_pubs(searchterm)
  File "/home/klc73/.local/lib/python3.6/site-packages/scholarly/_scholarly.py", line 149, in search_pubs
    return self.__nav.search_publications(url)
  File "/home/klc73/.local/lib/python3.6/site-packages/scholarly/_navigator.py", line 269, in search_publications
    return _SearchScholarIterator(self, url)
  File "/home/klc73/.local/lib/python3.6/site-packages/scholarly/publication_parser.py", line 53, in __init__
    self._load_url(url)
  File "/home/klc73/.local/lib/python3.6/site-packages/scholarly/publication_parser.py", line 59, in _load_url
    self._soup = self._nav._get_soup(url)
  File "/home/klc73/.local/lib/python3.6/site-packages/scholarly/_navigator.py", line 212, in _get_soup
    html = self._get_page('https://scholar.google.com{0}'.format(url))
  File "/home/klc73/.local/lib/python3.6/site-packages/scholarly/_navigator.py", line 164, in _get_page
    raise MaxTriesExceededException("Cannot Fetch from Google Scholar.")
scholarly._navigator.MaxTriesExceededException: Cannot Fetch from Google Scholar.
```

Thank you in advance for any help.

**Comment by samuelhaysom** [comment]
I am also running into this issue. Yesterday kjk11's code worked fine but today I am getting the same error that they did

**Comment by eduardozf** [comment]
Same happening  here! I noticed that Scholarly is sending the wrong url to ScraperApi
![Screenshot_2](https://user-images.githubusercontent.com/42107537/126386677-fa9bbb6c-d6ca-4c35-ad5c-8dfa52a47d9c.png)

**Comment by ipeirotis** [comment]
I just tried using ScraperAPI and Luminati proxies for exactly the same query. It seems that Luminati works better than ScraperAPI, as I also get blocked with ScraperAPI but not with Luminati.
