### ISSUE TITLE
search_pubs always gives MaxTriesExceededException

### ISSUE THREAD

**Issue by armandoanzellini** [scholarly-python-package/scholarly#294]
I've tried multiple different ways and search_pubs always seems to give a MaxTriesExceededException.

Even using code from the docs:
```python
search_query = scholarly.search_pubs('Perception of physical stability and center of mass of 3D objects')
```
and using code from the test_module.py:
```python
pubs = [p for p in scholarly.search_pubs(query)]
```
After getting this exception, I tried search_author to make sure
```python
search_query = scholarly.search_author('Steven A Cholewiak')
```
and it worked just fine, so the issue seems to be with search_pubs.

Using version 1.2.0

**Comment by ipeirotis** [comment]
What proxy service are you using ?

**Comment by armandoanzellini** [comment]
Tor_Internal

**Comment by ipeirotis** [comment]
Just tried it on Colab using Luminati and it worked without an issue. Especially for `search_pubs` you will need a reliable proxy.
