### ISSUE TITLE
Retrieve cites information of multiple authors.

### ISSUE THREAD

**Issue by joseph6x** [scholarly-python-package/scholarly#295]
Hi. 

I am trying to analyse auto-citation networks in my university using  the Google Scholar database through scholarly and I need to harvest information of at least 20 researchers (profile, publications and cites) as a concept-proof. However, I am running into some issues with Scholar blocking my requests, I tried with ScrapperAPI, TOR and FreeProxies but I have not been able to finish my experiment.

Can you recommend alternatives to achieve my goal?. in your opinion, is it feasible? 

If you have any ideas, please let me know I would be happy to contribute to this project.

**Comment by ipeirotis** [comment]
If you can survive using just the information from author profiles (i.e,. using just the `search_author` function and the corresponding `fill`) then you should be able to do it without proxies, but by simply spacing out your requests over time.

If you want to use the `search_pubs`, I would highly recommend creating an account with Luminati and using Luminati as proxy.

**Comment by arunkannawadi** [comment]
FreeProxies and Tor will not work sufficiently well for your purposes but ScraperAPI should be working reliably now with v1.4.2. Please give this another shot and feel free to open a new issue if you still have trouble using ScraperAPI.
