### ISSUE TITLE
search_pub_id()

### ISSUE THREAD

**Issue by ligon** [scholarly-python-package/scholarly#314]
I have really the same request as @nd7141.  At present with an *author* id I can use, e.g., `scholarly.search_author_id('jRwNfxwAAAAJ')` (and perhaps subsequently use fill) to learn what there is to learn about that author.  

I'm surprised that there's not an analogous method along the lines of `scholarly.search_pub_id('u5HHmVD_uO8C')`.    Ideally this would parse the information from https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=u5HHmVD_uO8C.  

At present one can feed urls of the above form into `scholarly.search_pubs_custom_url()`, but the parser breaks.

The custom url solution you offer above *does* work, but requires knowledge not only of the publication id, but also the author id of at least one of the authors.

_Originally posted by @ligon in https://github.com/scholarly-python-package/scholarly/issues/244#issuecomment-897867099_

**Comment by ltalirz** [comment]
opened https://github.com/scholarly-python-package/scholarly/pull/317

**Comment by ipeirotis** [comment]
Fixed in v.1.3.0
