### ISSUE TITLE
Fix failing tests during builds

### ISSUE THREAD

**Issue by ipeirotis** [scholarly-python-package/scholarly#337]
We need a more robust testing framework during the builds. Right now, correct code tends to generate failing tests due to proxy/network issues. If we can get proxies to work reliably, we can then ensure that failing tests are indeed an issue with the code.

**Comment by arunkannawadi** [comment]
+1. Does the Github Actions testing have access to your Luminati credentials? It should be possible to include them as a secret variable, which can used for testing. You can limit the testing so that every pull request doesn't automatically run them and use up your queries.

**Comment by ipeirotis** [comment]
Yes, my Luminati account is used. However, I do not think it works flawlessly.

These are the secrets and they are passed in the build script (https://github.com/scholarly-python-package/scholarly/blob/master/.github/workflows/pythonpackage.yml) like that:

```
          CONNECTION_METHOD: ${{ secrets.CONNECTION_METHOD }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
```

**Comment by arunkannawadi** [comment]
I setup my ScraperAPI credentials for Github Actions on my fork, and the unit tests pass on #333 branch. Could you change it to your ScraperAPI credential instead of Luminati when merging it? It'd be good to have a build passing badge for this repository!

**Comment by ipeirotis** [comment]
With 1.4.2 and migration to Scraper API the tests pass successfully and reliably. Moving forward, it would be a good approach to expect passing tests before accepting pull requests.
