### ISSUE TITLE
Deprecate Tor_External and Tor_Internal methods

### ISSUE THREAD

**Issue by arunkannawadi** [scholarly-python-package/scholarly#339]
It appears that the use of `Tor` is not effective anymore (https://github.com/scholarly-python-package/scholarly/discussions/334#discussioncomment-1384020) and does not appear to be actively checked or maintained. This is a proposal to remove the two `Tor` methods from `quickstart.rst` in v1.5 and deprecate them and marked them for removal for v2 of `scholarly` (unplanned yet) or by a specific date in the not so-near future. The methods should still stay in the codebase until we ensure no one is actively using these methods.

**Comment by alexanderustinov** [comment]
Hi, sorry to barge in on the closed issue, but Tor_Internal works OK for me when FreeProxies do not. Usecase - searching bibtex for articles by their title.
Am using fresh 1.5.1 from PyPi.

What should be done to preserve it?

**Comment by ma-ji** [comment]
Thanks for this amazing work! I would strongly suggest keeping the Tor options. It also works better for me than the other proxy options. I'm using an additional function to "reset" the tor if hitting a wall. Simply something like this: `os.system('systemctl reload tor')`.

**Comment by arunkannawadi** [comment]
I don't see the two Tor methods really going away ever. Adding a deprecation label simply allows us to release versions of `scholarly` that may be not 100% compatible with Tor. For example, a dependency package needed for Tor was not available on conda-forge and it wouldn't have been possible to get `scholarly` on conda-forge if we had fully supported Tor. The PyPI installation still supports it though.

The biggest implication of marking `Tor` as deprecated is that, we are not actively testing the newer features with Tor proxy setup. If any of you Tor users find it broken, we will rely on you to file a bug report, and hopefully a PR with the suggested fix as well.

**Comment by ipeirotis** [comment]
I think that having an external Tor proxy and using the `singleProxy` method (pointing to the Tor proxy) will work as well as the current `tor_external` approach.

**Comment by ma-ji** [comment]
> I think that having an external Tor proxy and using the `singleProxy` method (pointing to the Tor proxy) will work as well as the current `tor_external` approach.

That's what I'm using now. Not ideal but handy.

**Comment by ipeirotis** [comment]
> Not ideal but handy.

What part is not ideal in the setup? Do you find the renewal part of `tor_external` to be useful?
