### ISSUE TITLE
MaxRetryError

### ISSUE THREAD

**Issue by decause95** [scholarly-python-package/scholarly#342]
Hi,

Since upgrading to v1.4. I'm getting the following error:

`    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=51718): Max retries exceeded with url: /session/xxx/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd55de7c190>: Failed to establish a new connection: [Errno 61] Connection refused'))`

After doing my research, it looks like scrapper is being blocked by Captcha. I'm a beginner in coding so I'm havinng a lot of trouble in understanding the problem. Anyone else got the same issue? How can I help to get this solved?

Thank you,
Decause

**Comment by ipeirotis** [comment]
Use the ScraperAPI and try to see if it improves the results.
