### ISSUE TITLE
Update README.md and add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by ipeirotis** [scholarly-python-package/scholarly#343]
We should probably add a small piece of example code in the README.md, for example like the basic example:

```python
from scholarly import scholarly 

# Retrieve the author's data, fill-in, and print
# Get an iterator for the author results
search_query = scholarly.search_author('Steven A Cholewiak')
# Retrieve the first result from the iterator
first_author_result = next(search_query)
scholarly.pprint(first_author_result)
```

```python
# Retrieve all the details for the author
author = scholarly.fill(first_author_result )
scholarly.pprint(author)
```

```python
# Take a closer look at the first publication
first_publication = author['publications'][0]
first_publication_filled = scholarly.fill(first_publication)
scholarly.pprint(first_publication_filled)
```

```python
# Print the titles of the author's publications
publication_titles = [pub['bib']['title'] for pub in author['publications']]
print(publication_titles)
```

```python
# Which papers cited that publication?
citations = [citation['bib']['title'] for citation in scholarly.citedby(first_publication_filled)]
print(citations)
```

Then we can add some examples for publication searches, adding an example for the geckodriver and another example for the ScraperAPI proxy. At that point, we can then point to the full documentation for more extensive details.

Finally, we should create a CONTRIBUTING.md that describes the process of contributing code. This is mainly to instruct people to submit their PRs against the `develop` branch, and make sure that their code passes the tests. Then, we can remove the corresponding sections about testing, etc from the README.

**Comment by arunkannawadi** [comment]
A basic skeleton for CONTRIBUTING.md is done in #363. I don't think we should have examples in README, at least not as lengthy as the ones posted here. We can add a direct link to the quickstart page and say that the examples could be found there. If you agree, we can close this issue.
