### ISSUE TITLE
Missing publicaton ID from search results

### ISSUE THREAD

**Issue by mcopik** [scholarly-python-package/scholarly#350]
Hi,

I've been trying to identify a unique publication ID that I could use to store and retrieve citations later. In my usage scenario, I look for the paper by its name. However, it seems that such ID is not available when searching for a publication with a title, even though the `citedby_url` is available.

Example:
```python
>>> author = scholarly.search_author_id('JdXd8pQAAAAJ')
>>> scholarly.fill(author)
>>> pub = author['publications'][5]
>>> scholarly.pprint(pub)
{
 'author_pub_id': 'JdXd8pQAAAAJ:Tyk-4Ss8FVUC',
 'citedby_url': 'https://scholar.google.com/scholar?oi=bibs&hl=en&cites=12885035189720623002',
 'cites_id': ['12885035189720623002'],
 'filled': False,
 'num_citations': 6,
 'source': 'AUTHOR_PUBLICATION_ENTRY'
}
```

However, the same publication obtained through direct search has much more data, including a similar `citedby_url` with exactly the same ID, but it doesn't have the IDs.
```python
>>> search_query = scholarly.search_pubs('SeBS serverless')
>>> scholarly.pprint(next(search_query))
{
 'author_id': ['JdXd8pQAAAAJ', 'PyY2WfkAAAAJ', 'l3ZOsHkAAAAJ'],
  'citedby_url': '/scholar?cites=12885035189720623002&as_sdt=5,33&sciodt=0,33&hl=en',
 'eprint_url': 'https://arxiv.org/pdf/2012.14132',
 'filled': False,
 'gsrank': 1,
 'num_citations': 6,
 'pub_url': 'https://arxiv.org/abs/2012.14132',
 'source': 'PUBLICATION_SEARCH_SNIPPET',
 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3DSeBS%2Bserverless%26hl%3Den%26as_sdt%3D0,33&citilm=1&update_op=library_add&info=mqe0uTzX0LIJ&ei=YERnYYmGC4iKmgGYwLj4Dg&json=',
 'url_related_articles': '/scholar?q=related:mqe0uTzX0LIJ:scholar.google.com/&scioq=SeBS+serverless&hl=en&as_sdt=0,33',
 'url_scholarbib': '/scholar?q=info:mqe0uTzX0LIJ:scholar.google.com/&output=cite&scirp=0&hl=en'}
}
```

It looks like this particular feature is not implemented: https://github.com/scholarly-python-package/scholarly/blob/main/scholarly/publication_parser.py#L252

Is it an oversight or is there a fundamental problem and those IDs cannot be obtained in a consistent manner?
And is there a way to obtain publication ID when it has not been cited yet? The only way it seems to be to look for the first author with Scholar ID, and obtain the `author_pub_id` from their profile; which also breaks if none of  the authors have a Scholar ID :-)

**Comment by arunkannawadi** [comment]
Oh well, the third item in your search query 'SeBS serverless' appears to be a case where neither "Related articles" nor "All N versions" links are found, so there's no way to uniquely refer to it. It appears to be hosted on a University website, usually not the kind of article that we expect people to be interested in. But we should have a way to extract the cluster ID regardless whenever it is available.

**Comment by mcopik** [comment]
@arunkannawadi It's an arXiv paper. However, Google Scholar does catch the pdf on some arXiv aggregator website. We posted the paper on our websites, but this has not been detected by Scholar.

The third paper in the search query is a paper citing us; the name of our tool appears in the abstract. Indeed, this seems to be a user version pdf posted on the author's website and the conference proceedings are not yet online.

https://scholar.google.com/scholar?cluster=12885035189720623002&hl=en&as_sdt=0,5
