### ISSUE TITLE
Fetch journal metrics

### ISSUE THREAD

**Issue by arunkannawadi** [scholarly-python-package/scholarly#359]
We should to implement APIs to fetch journal metrics: https://scholar.google.com/citations?view_op=top_venues&hl=en

**Comment by giswqs** [comment]
This would a great feature to add. Very interested in this.

**Comment by arunkannawadi** [comment]
Good to know you're interested. The hardest part so far has been the designing of an API, given that there is an overall leaderboard for each language and in English, there are multiple categories and subcategories. 

My current idea is to have an API to list out all the possible categories and then another API that will accept one of those to return a list of journals and metrics. Any thoughts on what would be intuitive/useful are welcome.

**Comment by giswqs** [comment]
[Here](https://docs.google.com/spreadsheets/d/1uCEi3TsJCWl9QEZimvjlM8wjt7hNq3QvMqHGeT44HXQ/edit?usp=sharing) is a list of 160 journals under the 8 categories. I used to copy and paste those into the speadsheet. It would be nice if there is an API to retrieve the list of journals under each category and subcategory.

**Comment by arunkannawadi** [comment]
Thanks for the snippet. This isn't quite what we want though, since as a Google Scholar scraper, we want to get the information from (and only from) Google Scholar. This package seems to be downloading it from elsewhere into a database and running the query, which is bit more complex than scraping the Google Scholar page on demand.

**Comment by arunkannawadi** [comment]
@giswqs This should now be available in v1.6 through `get_journals`/`save_journals_csv` method in `scholarly` for each category and subcategory. You can see the (sub-)categories themselves using `get_journal_categories` method. Give it a try and please open an issue if you have any bugs with it.

**Comment by giswqs** [comment]
Fantastic! Will try it out. Thank you
