### ISSUE TITLE
Fetch Web of Science links and counts

### ISSUE THREAD

**Issue by arunkannawadi** [scholarly-python-package/scholarly#370]
A relatively new feature in Google Scholar is to report the Web of Science citation counts (and provide WoS link) to papers in PUBLICATION_SEARCH_SNIPPET. We should be able to include this in v1.5

https://scholar.google.com/scholar?q=Machine-learned+epidemiology:+real-time+detection+of+foodborne+illness+at+scale&hl=en

![image](https://user-images.githubusercontent.com/5103390/140980290-9078c711-86d6-4b28-89df-a1a20f47ba06.png)

**Comment by arunkannawadi** [comment]
My hypothesis is that the introduction of this feature (not seen until yesterday) is likely the cause of #368

**Comment by ipeirotis** [comment]
My understanding is that WoS links only appear when you are in a subnet that provides access to WoS (typically an academic campus)

**Comment by arunkannawadi** [comment]
Ah, that makes sense. However, this is still new since I have not seen this before from university network, so this is nevertheless a new feature. But restricted access likely means this is almost never going to work with proxy services (it's a `/scholar?` page).

**Comment by ipeirotis** [comment]
No, definitely not new. See https://github.com/scholarly-python-package/scholarly/issues/58

**Comment by arunkannawadi** [comment]
Strange! May be I have only been checking Google Scholar from my home network. Closing it then.

**Comment by ipeirotis** [comment]
I think you also need to login to your university library (or WoS), so that Google can recognize that you have access to the WoS data. No idea how Google detects that
