### ISSUE TITLE
Search authors by organization

### ISSUE THREAD

**Issue by arunkannawadi** [scholarly-python-package/scholarly#372]
**A `search_authors_by_organization` function that will list all authors belonging to an organization**
E.g., the list of everyone who are at Princeton: https://scholar.google.com/citations?view_op=view_org&hl=en&org=4836318610601440500

**Describe the solution you'd like**
This will take in an organization id (expected in v1.5) and give an iterator similar to `_SearchScholarIterator` that can iterate through the profiles

**Do you plan on contributing?**
- [x] Yes, I plan to contribute towards this feature in the next couple of days.

**Comment by timsainb** [comment]
Is there any way to search for a specific author at an institution?

**Comment by ipeirotis** [comment]
Add the domain name together with the author name.
