### ISSUE TITLE
Add package to conda-forge

### ISSUE THREAD

**Issue by giswqs** [scholarly-python-package/scholarly#377]
Any plan to add the package to [conda-forge](https://conda-forge.org)? I can't add scholarly as a package dependency until it is available on conda-forge. 
https://github.com/conda-forge

**Comment by arunkannawadi** [comment]
I think that's a good idea and we should be able to do that. I cannot promise to do this until January 2022. Does that timescale work for you? If other developers could it do before that, that'd be helpful!

**Comment by giswqs** [comment]
I just checked the dependencies in [requirements.txt](https://github.com/scholarly-python-package/scholarly/blob/main/requirements.txt) and found that [stem](https://github.com/torproject/stem) and [free-proxy](https://github.com/jundymek/free-proxy) are not available on [conda-forge](https://conda-forge.org/feedstock-outputs/). Otherwise, I can help add scholarly to conda-forge. stem and free-proxy need to be added to conda-forge first before scholarly.

**Comment by arunkannawadi** [comment]
Would it help if we made those optional? They are both related to proxy services and should be not strictly required. We are planning to drop Tor anyway, can therefore drop [stem](https://github.com/torproject/stem) completely if needed.

**Comment by giswqs** [comment]
Yes, it would be great if you can make `stem` and `free-proxy` optional. Once you make them optional and release a version to PyPI, I can help submit scholarly to conda-forge.

**Comment by arunkannawadi** [comment]
On second thoughts, making `free-proxy` optional might break existing applications that use `scholarly`. It is perhaps easier to add `free-proxy` to conda-forge (all its dependencies are already on conda-forge). `stem` can become an optional dependency since Tor methods are deprecated with the next release.

**Comment by arunkannawadi** [comment]
PR adding `scholarly` and `free-proxy` to `conda-forge` is [here](https://github.com/conda-forge/staged-recipes/pull/17289). Unable to get any of the checks passed, but will get to it soom

**Comment by arunkannawadi** [comment]
Thanks for the nudge @giswqs . `scholarly` is now on `conda-forge` and please feel free to use it as a dependency in your code.

**Comment by giswqs** [comment]
That's great. Thanks a lot!
