### ISSUE TITLE
Incorrect research interests

### ISSUE THREAD

**Issue by giswqs** [scholarly-python-package/scholarly#394]
When a scholar does not list research interests on their profile, the `scholarly.search_author()` function returns an `interests` list with the scholar name in it, which is incorrect. I would expect the list to be empty. The results from `scholarly.search_author()` and `scholarly.search_author_id()` are inconsistent. See the screenshot below. 

```python
from scholarly import scholarly
search_query = scholarly.search_author('Albert Einstein')
scholarly.pprint(next(search_query))
```

```python
author = scholarly.search_author_id('do7frTMAAAAJ')
scholarly.pprint(author)
```

![image](https://user-images.githubusercontent.com/5016453/150272687-bc325d48-52bc-4e40-a380-c328d9432d6e.png)

**Comment by meShubhamJha** [comment]
Can I take this bug?

**Comment by ipeirotis** [comment]
By all means, go ahead!

**Comment by arunkannawadi** [comment]
@meShubhamJha do you have a rough estimate on when you'd be able to work on this? I plan on releasing a minor version within the next two weeks with some new features. It'd be good to get this bug fix in for the release. If you need help on where to look in, let me know.
