### ISSUE TITLE
Author search fails for researchers with more than 1000 publications

### ISSUE THREAD

**Issue by kocmitom** [scholarly-python-package/scholarly#414]
When filling author information after search_author, for the author that has more than 1000 publications, it fails on an error:
`ValueError: invalid literal for int() with base 10:`

The problem is on lines: 
https://github.com/scholarly-python-package/scholarly/blob/5ca61183a0a435f9128f17e58a166274864c97a2/scholarly/author_parser.py#L138
https://github.com/scholarly-python-package/scholarly/blob/5ca61183a0a435f9128f17e58a166274864c97a2/scholarly/author_parser.py#L140

Because Google is using the dot as a thousand separator. See here (available/not available papers):
https://scholar.google.cz/citations?hl=en&user=f4KlrXIAAAAJ

**Comment by arunkannawadi** [comment]
Thanks for bringing this up. This will be fixed in v1.6.1 which will be released in a couple of hours.

**Comment by arunkannawadi** [comment]
For reasons unknown , the release v1.6.1 is not appearing via pip or conda. Please use the direct installation from github. Instructions are on the README.
