### ISSUE TITLE
Multiple Versions of a Paper

### ISSUE THREAD

**Issue by picheny-nyu** [scholarly-python-package/scholarly#427]
It looks like this was supported a few years ago but then there is a comment in one of the posts that suggests this functionality is now gone. Can someone tell me what the status is?

Thanks
Michael Picheny

**Comment by arunkannawadi** [comment]
You should still be able to fetch them. See the doc here: https://github.com/scholarly-python-package/scholarly/blob/de817e715a06e32aa4a938408fa6763c375ef27c/scholarly/data_types.py#L170-L185

**Comment by picheny-nyu** [comment]
Thanks! What do you mean by a "good" proxy setup? I have been using FreeProxy (I don't have any of the others).

**Comment by arunkannawadi** [comment]
I meant it in the sense that looking for all versions of a paper is one of those things that Google Scholar actively tries to block. FreeProxy should probably suffice, but is not always reliable. If that doesn't work, you might want to try it with `ScraperAPI` or `Luminati`.

**Comment by picheny-nyu** [comment]
Thank you. One more question - I don't see how to get the "cites_id" from the api. Could you point me to an example?

Thanks
Michael

**Comment by arunkannawadi** [comment]
If you are starting from your profile, you can follow this example in the quickstart. The `pub` variable at the end of the example should have a key that is `cites_id`.
https://scholarly.readthedocs.io/en/stable/quickstart.html#example

**Comment by arunkannawadi** [comment]
@picheny-nyu Can we close this issue?

**Comment by picheny-nyu** [comment]
Yes we may!
