### ISSUE TITLE
Can't scrape more than ~1000 `citedby` papers

### ISSUE THREAD

**Issue by jjshoots** [scholarly-python-package/scholarly#444]
**Describe the bug**
I'm trying to scrape all papers that cite [this paper](https://arxiv.org/abs/1606.01540) which has ~4.5k citations, but scholarly only allows me to get the first ~1000 papers, and truncates the rest.

**To Reproduce**
```python
from scholarly import ProxyGenerator, scholarly
# parse through all papers that cite this paper
original_paper = next(scholarly.search_pubs("Openai Gym"))
for i, paper in enumerate(scholarly.citedby(original_paper)):
    print(i)
```

**Expected behavior**
`i` reaches values of >4k.

**Desktop (please complete the following information):**
 - Proxy service: ScraperAPI
 - python version: 3.10
 - OS: Ubuntu 22.04
 - Version 1.7.2

**Do you plan on contributing?**
Your response below will clarify whether the maintainers can expect you to fix the bug you reported.
- [ ] Yes, I will create a Pull Request with the bugfix if I get pointed in the right direction on how this can be fixed. I've looked at the source code and can't figure out where the issue is.

**Comment by arunkannawadi** [comment]
It doesn't appear to be `scholarly`'s fault. Just going through the full citation list for this paper, there are simply no more results showing up after the 100th page.

https://scholar.google.com/scholar?start=990&hl=en&as_sdt=80000005&sciodt=0,23&cites=11927109203784430218&scipsc=

**Comment by arunkannawadi** [comment]
This page appears to say it's page 101 but shows no results. https://scholar.google.com/scholar?start=2200&hl=en&scisbd=1&as_sdt=80000005&sciodt=0,23&cites=11927109203784430218&scipsc=

**Comment by jjshoots** [comment]
That's interesting, thanks for the insight and _very_ quick response!

**Comment by jkterry1** [comment]
Is there any way to work around this or have you ever seen it before? Google indicates a ton more citations then that, and being able to more thoroughly analyze these would be incredibly helpful to something we're working on right now.
<img width="810" alt="Screen Shot 2022-10-17 at 5 42 06 PM" src="https://user-images.githubusercontent.com/19422700/196289749-37c23731-36c1-4dd0-a123-8b3a9262c092.png">

**Comment by arunkannawadi** [comment]
A solution however is to do multiple queries by restricting the year ranges and sorting them by relevance and date. And hopefully with those you can recover all citations. You can use `search_citedby` function and pass in `year_low` and `year_high` keywords to do this. You'll need to get the `publication_id` for the paper, which should be in `original_paper`.

**Comment by jjshoots** [comment]
That sounds like a decent solution, I'll give it a shot, thank you!

**Comment by arunkannawadi** [comment]
The documentation for `search_citedby` is similar to this one: https://github.com/scholarly-python-package/scholarly/blob/main/scholarly/_scholarly.py#L93-L112

**Comment by jjshoots** [comment]
Hi @arunkannawadi, I can't seem to find `publication_id` within `original_paper`, is it known under a different name? The following is the output when print `original_paper`.

```yaml
{'author_id': ['uyYPun0AAAAJ', '', '_iYrAxEAAAAJ'],
 'bib': {'abstract': 'In this article we introduce the Arcade Learning '
                     'Environment (ALE): both a challenge problem and a '
                     'platform and methodology for evaluating the development '
                     'of general, domain-independent AI technology. ALE '
                     'provides an interface to hundreds of Atari 2600 game '
                     'environments, each one different, interesting, and '
                     'designed to be a challenge for human players. ALE '
                     'presents significant research challenges for '
                     'reinforcement learning, model learning, model-based '
                     'planning, imitation learning, transfer learning, and '
                     'intrinsic',
         'author': ['MG Bellemare', 'Y Naddaf', 'J Veness'],
         'pub_year': '2013',
         'title': 'The arcade learning environment: An evaluation platform for '
                  'general agents',
         'venue': 'Journal of Artificial …'},
 'citedby_url': '/scholar?cites=10877906446132695264&as_sdt=5,33&sciodt=0,33&hl=en',
 'container_type': 'Publication',
 'eprint_url': 'https://www.jair.org/index.php/jair/article/download/10819/25823',
 'filled': False,
 'gsrank': 1,
 'num_citations': 2635,
 'pub_url': 'https://www.jair.org/index.php/jair/article/view/10819',
 'source': <PublicationSource.PUBLICATION_SEARCH_SNIPPET: 'PUBLICATION_SEARCH_SNIPPET'
>,
 'url_add_sclib': '/citations?hl=en&xsrf=&continue=/scholar%3Fq%3DThe%2Barcade%2Blearn
ing%2Benvironment:%2BAn%2Bevaluation%2Bplatform%2Bfor%2Bgeneral%2Bagents%26hl%3Den%26a
s_sdt%3D0,33&citilm=1&update_op=library_add&info=4NCrdUcW9pYJ&ei=XNBNY5-4BIn8mgGU_KHAA
g&json=',
 'url_related_articles': '/scholar?q=related:4NCrdUcW9pYJ:scholar.google.com/&scioq=Th
e+arcade+learning+environment:+An+evaluation+platform+for+general+agents&hl=en&as_sdt=
0,33',
 'url_scholarbib': '/scholar?hl=en&q=info:4NCrdUcW9pYJ:scholar.google.com/&output=cite
&scirp=0&hl=en'}
```

**Comment by arunkannawadi** [comment]
Try one of 10877906446132695264 or 11927109203784430218 or 80000005. Of course, get the first 10 results to compare which the correct one is.

**Comment by jjshoots** [comment]
Gotcha, but my question was where did you find the number in the first place? Apologies if this wasn't clear.

**Comment by arunkannawadi** [comment]
Actually, it should be 11927109203784430218. Now I remember why the documentation is poor. It is whatever follows after cites= in the URLs I pasted, but there's no easy way to get that from `original_paper`.

**Comment by jjshoots** [comment]
Is it not `10877906446132695264` instead?

In any case, would you like me to make a PR fixing `citedby` to be able to handle papers with more than 1k citations? The technique I'm currently using is to simply use `search_citedby` in 1 year increments. This can be added easily by first checking if the paper has more than 1k citations to beginwith, and then choosing to search using the `search_citedby` with year increments.

**Comment by arunkannawadi** [comment]
> Is it not 10877906446132695264 instead?

The `original_paper` output you posted seems to be for the paper titled 'The arcade learning environment: An evaluation platform for general agents' and not 'Openai Gym'.

> In any case, would you like me to make a PR fixing citedby to be able to handle papers with more than 1k citations?

Sure, that would be great!
But I still think that that cannot handle if there are more than 1000 citations within one year. That's going to be the case for 'Openai gym' paper.

**Comment by jjshoots** [comment]
Hi, I'm using scraperAPI, I've actually just scraped all 4k+ citations using the `search_citedby` technique you've mentioned, which was how I know that the solution works. I'll give it a shot scraping all 4k citations in one go using the new version probably in a couple weeks when the credits are expiring. :) Thanks a ton for the help!

**Comment by arunkannawadi** [comment]
Sure, when you have a success with the new version for a different paper with more than 1000 citations, please let me know! :-)
