### ISSUE TITLE
Scholarly 1.7.3 and 1.7.4 are not on PyPI

### ISSUE THREAD

**Issue by frafra** [scholarly-python-package/scholarly#460]
**Describe the bug**
Scholarly 1.7.3 and 1.7.4 are not on PyPI.

**Comment by arunkannawadi** [comment]
1.7.3 is on PyPI: https://pypi.org/project/scholarly/1.7.3/
1.7.4 is not, since I missed updating the setup.py
1.7.5 is now the latest release and is on PyPI: https://pypi.org/project/scholarly/1.7.5/
