### ISSUE TITLE
If user has 0 citations, the "citations count" becomes misaligned

### ISSUE THREAD

**Issue by bgreenawald-vt** [scholarly-python-package/scholarly#481]
**Describe the bug**
If a user has 0 citations for a year (but has previously had citations), when the citation counts are filled (using `scholarly.fill(_, sections=['counts'])`), the `cites_per_year` value in the results dictionary will not be correctly aligned. For example, if the user has the following counts: 2017: 1, 2018: 0, 2019: 9, the results produced by this package will be {2017: 1, 2018: 9}.

**To Reproduce**
Find any user who has 0 citations for a year but does have citations for a previous and following year, then run

```
author = scholarly.search_author_id('AUTHOR_ID')
scholarly.pprint(scholarly.fill(author, sections=['counts', 'indices']))
```

**Expected behavior**
The `cites_per_year` result should account for years with 0 citations.

**Screenshots**
![image](https://user-images.githubusercontent.com/122644400/212413006-48e1fbed-e744-4fc3-8a12-d5b5c8ab006b.png)
![image](https://user-images.githubusercontent.com/122644400/212413107-6d0adef3-71db-4b9d-86cc-f22ece18d9bf.png)

**Desktop (please complete the following information):**
 - Proxy service: FreeProxy
 - python version: 3.10.6
 - OS: Ubuntu
 - Version  Ubuntu 18.04.6 LTS

**Do you plan on contributing?**
Your response below will clarify whether the maintainers can expect you to fix the bug you reported.
- [ ] Yes, I will create a Pull Request with the bugfix.

**Comment by arunkannawadi** [comment]
Thank you for this bug report. This is being fixed now, triggering a v1.7.10 release.
