### ISSUE TITLE
Add the full author list of each paper for Author.publications?

### ISSUE THREAD

**Issue by Trenchhhhh** [scholarly-python-package/scholarly#485]
Thanks so much for this useful code, I really appreciate it.

In my research field, the first author is considered to be rather important, and typically each paper won't be completed by a large number of authors, as the cases in some areas. When I tried to retrieve all the first author articles of a person, however, the Author.publications didn't give a full author list for each paper, which made it hard for me to extract the first author papers. I tried solving this by using the search_pubs for each paper, but the blocking issue was a big problem. Therefore, I was wondering if you could add the full author list of each paper for Author.publications? Thank you!

**Comment by arunkannawadi** [comment]
I don't fully follow the request. The incomplete list of authors listed on the publication will include the first few authors, which should be sufficient to identify the first author's name. I don't see why not having the full list of authors prevents this.

However, if you do need the full list of authors for a publication picked from a Google Scholar's profile page, then simply do something like this

```python
for pub in author["publications"]:
    scholarly.fill(pub)
```

which will fill the complete list of authors among other details. This has much lower chances of getting blocked compared to `search_pubs`.

**Comment by arunkannawadi** [comment]
Marking this issue as invalid and closing because this feature already exists as I mentioned above. If I misunderstood the request, please feel free to reopen it again.
