### ISSUE TITLE
SSLCertVerificationError with RandomProxies Sample Code

### ISSUE THREAD

**Issue by qapl1209** [scholarly-python-package/scholarly#503]
**Describe the bug**
SSLCertVerificationError when running sample code, specifically: 
- SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997).
Attempted to download certifi and Install Certifications.download to no avail, is this a local network issue?

**To Reproduce**
![image](https://github.com/scholarly-python-package/scholarly/assets/17038232/373f2afe-d33f-4496-85ce-0a900a431b2b)

**Expected behavior**
Should return true with working proxy.

**Screenshots**

**Desktop (please complete the following information):**
 - Proxy service: scholarly
 - python version: 3.10.9
 - OS: Windows 11
 - Version 1.7.11

**Do you plan on contributing?**
Your response below will clarify whether the maintainers can expect you to fix the bug you reported.
- [ ] Yes, I will create a Pull Request with the bugfix.

**Additional context**

**Comment by arunkannawadi** [comment]
Is this a persistent issue? You might have just been unlucky and if you run it again after some time, it should work.

**Comment by qapl1209** [comment]
The issue is persistent no matter how many times I run it. I'm also using Jupyter Notebooks but I don't think that should interfere with anything.

**Comment by qapl1209** [comment]
Never mind, I figured it out. It was a local network setting issue, thanks for the attention!
