### ISSUE TITLE
Adding number of citations from web of science

### ISSUE THREAD

**Issue by AntjeGaertner** [scholarly-python-package/scholarly#58]
It would be a great addition to also query the number of citations from the web of science core collection, which I am sure a lot of people would appreciate as it shows the number of citations in the peer-reviewed literature only.

The number of web of science citations are automatically a part of the google scholar search result if one is using an institutional Wifi connection (so no need for passwords) and if it is included in the core collection.

I am asking for this tool, as I am unable the use the web of science API, as I, and I think most people, have only institutional access to the web of science. Unfortunately, I am too much of a novice to web data mining to add this feature myself. So, I would be very grateful!

**Comment by ipeirotis** [comment]
I think it would be super hard to do that at any level of scale using a direct institutional connection. Google Scholar is pretty aggressive in asking for CAPTCHAs and blocking robots. Even if we could implement this functionality, it would be super hard to test, as it relies on the call originating from an institution that has access to WoS. There is even the risk of Google blocking permanently the IP from the institution.

**Comment by ipeirotis** [comment]
I have examined that issue, and requires someone with institutional connection that allows access to WoS. At the same time, Google blocks quickly such searches, and once we use a proxy, the WoS values disappear. 

I do not see a realistic path for implementing this.
