### ISSUE TITLE
Github Actions should also check build on Windows and Mac

### ISSUE THREAD

**Issue by ipeirotis** [scholarly-python-package/scholarly#89]
Right now, we only run tests using `ubuntu-latest`. The build process should be modified to also test on windows and mac. This is especially important given that we are increasingly using tor, which has different installation instructions across these platforms.

**Comment by ipeirotis** [comment]
There seem to be some Windows/Mac issued when using selenium/geckodriver in Windows and Mac:
https://github.com/scholarly-python-package/scholarly/issues/211
https://github.com/scholarly-python-package/scholarly/issues/196
and it would be good to configure the test suite to run such tests in Windows/Mac to see how prevalent they are.

**Comment by arunkannawadi** [comment]
With Tor getting deprecated in 1.5, extending the Github Actions to build the package on other OS becomes trivial. So this should be doable with 1.5 release.
