### ISSUE TITLE
Update package on PyPI

### ISSUE THREAD

**Issue by ipeirotis** [scholarly-python-package/scholarly#90]
The current version of scholarly available on PyPI (0.2.5; released: Jun 6, 2019) has not been updated for a while. We should create a maintenance release that includes some of the new features (e.g., proxies) and fixing some of the bugs.

**Comment by ipeirotis** [comment]
@OrganicIrradiation Could you please add me or @silvavn or @bielsnohr as owners for the package on PyPI?

My PyPI username is `ipeirotis`.

@silvavn or @bielsnohr could you please give your usernames for PyPI?

**Comment by OrganicIrradiation** [comment]
Added

**Comment by silvavn** [comment]
my PyPI is `vsilva`

**Comment by ipeirotis** [comment]
Added

**Comment by bielsnohr** [comment]
My PyPI username is `bielsnohr` . Thanks!

**Comment by ipeirotis** [comment]
@bielsnohr added

**Comment by ipeirotis** [comment]
@silvavn Since you created the v0.3 release, could you also please push it to PyPI?

**Comment by silvavn** [comment]
@ipeirotis I will upload it when we integrate #98

**Comment by ipeirotis** [comment]
@OrganicIrradiation Would it be possible to give admin rights for the Github repository? It seems that we just have write permissions, and we need Admin rights to setup CI/CD workflows for publishing to PyPI.

**Comment by OrganicIrradiation** [comment]
@ipeirotis You are listed as an "Owner" on PyPi. On Github, the only option I see available is collaborator. Recommendations?

**Comment by ipeirotis** [comment]
@OrganicIrradiation I see what is the issue.

I created an "organization" called "scholarly-python-package" and I invited you there as an owner. Could you accept and then transfer ownership of the scholarly repository to the organization?

**Comment by OrganicIrradiation** [comment]
Thanks for doing all of this, @ipeirotis (and @bielsnohr and @silvavn)! I've transferred ownership to https://github.com/scholarly-python-package/scholarly

**Comment by ipeirotis** [comment]
thanks @OrganicIrradiation 

@silvavn I created a workflow which should post to PyPI any tagged commit. Once we are done with the last couple of PR and the bug in the issues, let's create v.0.3.1 and push it to PyPI.

**Comment by ipeirotis** [comment]
Yeah! Autopublishing of the tagged versions to PyPI works! :-)

Version 0.3.1 is now available on PyPI!

Thanks for all the hard work @silvavn
